### ISSUE TITLE
New T-Rex dual mining Request!

### ISSUE THREAD

**Issue by gigabyteminer** [trexminer/T-Rex#1053] opened 2022-02-06 20:50 UTC
Can t-rex add dual mining for ton + alph / zil + alph / zil + ton 50/50. These coins are not influenced on lhr cards and more profitable.

**Comment by trexminer** [comment] 2022-02-09 15:26
Duplicate of https://github.com/trexminer/T-Rex/issues/1035
(ZIL may or may not be supported)

**Closed by trexminer** 2022-02-09 15:26 UTC
