### ISSUE TITLE
how to use a network proxy with T-rex

### ISSUE THREAD

**Issue by xiaod-dev** [trexminer/T-Rex#520] opened 2021-07-02 10:15 UTC
My network is not stable to connecting with some pools, so I am considering use a VPN to accelerate the speed. Now I have a Http Proxy and Sock5 proxy endpoint, How can I connecting pools with these network proxy tools with T-rex?

**Comment by trexminer** [comment] 2021-07-03 13:56
Duplicate of https://github.com/trexminer/T-Rex/issues/399

**Closed by trexminer** 2021-07-03 13:56 UTC

**Comment by xiaod-dev** [comment] 2021-07-03 14:10
Thanks for reply. I 've looked at #139 , It seems still open. So the socks5 proxy is still WIP?

**Comment by trexminer** [comment] 2021-07-03 14:14
> So the socks5 proxy is still WIP?

It's not. We haven't started implementing it.

**Comment by XFNeo** [comment] 2022-03-09 22:12
Hi @trexminer any updates?
