### ISSUE TITLE
Windows 10 Defender is blocking T-Rex saying "Detected: PUA:Win32/Vigua.A"

### ISSUE THREAD

**Issue by zigzag-way** [trexminer/T-Rex#393] opened 2021-04-12 08:36 UTC
![image](https://user-images.githubusercontent.com/13463960/114365389-b92d4800-9b7a-11eb-9e1e-8996363c0f4f.png)

Adware inside?!

**Comment by trexminer** [comment] 2021-04-12 09:58
Duplicate of https://github.com/trexminer/T-Rex/issues/384

**Closed by trexminer** 2021-04-12 09:58 UTC
