### ISSUE TITLE
Windows Defender reports Trojan:Win32/Detplock, t-rex.exe is deleted

### ISSUE THREAD

**Issue by cyprus00** [trexminer/T-Rex#163] opened 2021-01-28 19:01 UTC
miner crashed yesterday, I believe windows deleted the t-rex.exe after detecting the Detplock Trojan. may be false positive, would appreciate some feedback

**Comment by trexminer** [comment] 2021-01-29 04:59
Duplicate of https://github.com/trexminer/T-Rex/issues/149

**Closed by trexminer** 2021-01-29 04:59 UTC
