### ISSUE TITLE
3080 without LHR reduces its power without cause

### ISSUE THREAD

**Issue by JPARKANTOS** [trexminer/T-Rex#903] opened 2021-12-03 04:52 UTC
I run the miner on windows 11, with the drivers 497.09, and the miner 0.24.7. The problem is that the mining runs correctly for a while and then out of nowhere it goes from 92-93 mh / s to only 47 mh / s, the temperatures are completely normal and the card behaves well in stressful situations as well as the source, does this problem happen to someone else?

**Comment by trexminer** [comment] 2021-12-03 06:33
New drivers cause unstable behaviour at high LHR values, downgrade to 472.12 for better results.

**Comment by trexminer** [comment] 2021-12-03 06:33
Duplicate of https://github.com/trexminer/T-Rex/issues/845

**Closed by trexminer** 2021-12-03 06:33 UTC
