### ISSUE TITLE
The GPU is abnormal, causing t-rex to restart. Is there any solution

### ISSUE THREAD

**Issue by romeoblog** [trexminer/T-Rex#945] opened 2021-12-19 10:12 UTC
20211219 17:26:36 TREX: Can't find nonce with device [ID=5, GPU #5], cuda exception: CUDA_ERROR_UNKNOWN
20211219 17:26:36 WARN: Miner is going to shutdown...
20211219 17:26:36 WARN: NVML: can't get fan speed for GPU #1, error code 999
20211219 17:26:37 WARN: NVML: can't get power for GPU #1, error code 999
20211219 17:26:36 Main loop finished. Cleaning up resources...
20211219 17:26:37 ApiServer: stopped listening on 192.168.10.15:4067
20211219 17:26:41 T-Rex finished.
20211219 17:26:41 WARN: WATCHDOG: T-Rex does not exist anymore, restarting...
20211219 17:26:44 T-Rex NVIDIA GPU miner v0.24.8  -  [Windows]
20211219 17:26:44 r.24882b3a9e07
20211219 17:26:44 
20211219 17:26:44 
20211219 17:26:44 NVIDIA Driver v472.12
20211219 17:26:44 
20211219 17:26:44 + GPU #0: [00:01.0|1f06] Colorful GeForce RTX 2060 SUPER, 8192 MB
20211219 17:26:44 + GPU #1: [00:03.0|1f06] Colorful GeForce RTX 2060 SUPER, 8192 MB
20211219 17:26:44 + GPU #2: [00:04.0|1f06] Colorful GeForce RTX 2060 SUPER, 8192 MB
20211219 17:26:44 + GPU #3: [00:05.0|1f06] Colorful GeForce RTX 2060 SUPER, 8192 MB
20211219 17:26:44 + GPU #4: [00:06.0|1f06] Colorful GeForce RTX 2060 SUPER, 8192 MB
20211219 17:26:44 + GPU #5: [00:07.0|1f06] Colorful GeForce RTX 2060 SUPER, 8192 MB
20211219 17:26:44 + GPU #6: [00:08.0|1f06] Colorful GeForce RTX 2060 SUPER, 8192 MB
20211219 17:26:44 + GPU #7: [00:09.0|1f06] Colorful GeForce RTX 2060 SUPER, 8192 MB
20211219 17:26:44 
20211219 17:26:44 WARN: DevFee 1% (ethash)

**Comment by romeoblog** [comment] 2021-12-19 10:18
GPU #5: Colorful RTX 2060 SUPER - 43.85 MH/s, [T:51C, P:100W, F:80%, E:443kH/W], 928/928 R:0%

**Comment by trexminer** [comment] 2021-12-19 10:21
Please use search before posting a new issue
Duplicate of https://github.com/trexminer/T-Rex/issues/226

**Closed by trexminer** 2021-12-19 10:21 UTC
