### ISSUE TITLE
high RAM usage

### ISSUE THREAD

**Issue by mikimil** [trexminer/T-Rex#284] opened 2021-03-12 12:26 UTC
![ram trex](https://user-images.githubusercontent.com/25346397/110939037-109a8700-8335-11eb-8f5f-cbfcc2394b81.PNG)
about 18gb seems a bit much (with 4 graphics cards, win 10, 32gb ram, version t-rex-0.19.11-win-cuda11.1 ).
any tipps ?

**Comment by trexminer** [comment] 2021-03-12 14:00
This is most likely a duplicate of https://github.com/trexminer/T-Rex/issues/262. Try running the miner with `--no-nvml` and see if it fixes the issue. If so, you can use an older video driver that doesn't exhibit memory leaks.

**Comment by mikimil** [comment] 2021-03-13 09:34
It has the high ram usage on start up and it does seem to climb over time. The allocated memory seem to be so much higher than it has to be. so i dont think it's the same problem.

**Comment by luiizneres** [comment] 2021-08-04 23:31
> It has the high ram usage on start up and it does seem to climb over time. The allocated memory seem to be so much higher than it has to be. so i dont think it's the same problem.

dear friend did you manage to solve the problem?

**Comment by trexminer** [comment] 2021-08-05 07:32
High amount of memory reported in what ProcessExplorer calls "Private Bytes" (the amount of Page file space that is allocated to the process) is normal, and it's the amount of RAM the miner actually needs plus all memory allocated on the GPUs. What you really need to monitor is "Working Set" (not displayed in the screenshot) and it's typically about 200-300MB, but can grow in case your video drivers have a memory leak in them (see #262).

**Closed by trexminer** 2021-08-05 07:32 UTC
