### ISSUE TITLE
BUSID Error

### ISSUE THREAD

**Issue by skhalid93** [trexminer/T-Rex#591] opened 2021-08-21 20:17 UTC
Been getting "Can't start miner, failed to initialize device map: can't get busid, code -6" error on v0.21.4 (windows).

Looks like downgrading to anything below v0.21.5 fixes the issue as I downgraded to v0.21.4 and it's now stable with no errors. I have seen other issue posts stating that this method doesn't work for them, but it did for me. 

Just wanted to let y'all know. 

UPDATE - This did not work. It did allow the miner to run a little longer, but it still produces code -6 error.

**Comment by trexminer** [comment] 2021-08-22 05:02
Duplicate of https://github.com/trexminer/T-Rex/issues/529

**Closed by trexminer** 2021-08-22 05:02 UTC

**Comment by WiseKai** [comment] 2022-04-21 08:20
Updating drivers worked for me.
