### ISSUE TITLE
Watchdog restarts needlessly 0.10.2

### ISSUE THREAD

**Issue by nvOC-Stubo** [trexminer/T-Rex#19] opened 2019-05-16 10:26 UTC
I am mining on nvOC (Ubuntu) so I had to rename the executable from "t-rex" to "ccminer". I am seeing this in the output constantly:

WARN: WATCHDOG: T-Rex does not exist anymore, restarting...

I suspect the issue is the renaming. I am currently using the "--no-watchdog" option to get around the issue and it is mining just fine. Does the watchdog implementation look for the name of the executable as a process or is my problem elsewhere?

**Comment by trexminer** [comment] 2019-05-17 15:18
It's a known problem in 0.10.2, we'll try to fix it in the next release

**Comment by trexminer** [comment] 2019-05-20 06:33
The problem should be fixed in 0.11.0
Please let me know if you still experience it

**Comment by nvOC-Stubo** [comment] 2019-05-20 12:17
The initial testing looks good as I have seen no unnecessary restarts yet.

**Comment by trexminer** [comment] 2019-05-20 12:31
Thanks for letting us know

**Closed by trexminer** 2019-05-20 12:31 UTC

**Comment by system4id** [comment] 2020-12-10 07:04
The same issue on 0.19.1 cuda 10. What I have to do?

**Comment by trexminer** [comment] 2020-12-10 09:00
@system4id could you please provide the log file / screenshot?

**Comment by system4id** [comment] 2020-12-10 10:12
![image](https://user-images.githubusercontent.com/16144580/101758411-5acb5c80-3ae9-11eb-9be4-f78e217bf751.png)

**Comment by trexminer** [comment] 2020-12-10 10:43
I'm guessing you have the latest video drivers installed v460.xx? If so, it's a known issue, hopefully NVIDIA will fix it.

**Comment by system4id** [comment] 2020-12-10 10:44
Yes, 460x version

**Comment by turbare** [comment] 2020-12-10 11:31
Yup, I just updated today and it stopped working properly, getting the message above.
Nvidia drivers 460.79.

Why do you expect NVIDIA to fix this? Isn't it related to the miner itself? Or some bug in the CUDA stuff?

**Comment by trexminer** [comment] 2020-12-10 11:35
This issue affects many other mining software, so that sort of indicates the issue is in the drivers. It could still be miner related, so further investigation is required.

**Comment by turbare** [comment] 2020-12-10 11:58
Any workaround in the meantime? I tried adding --no-watchdog at the end of the line but that doesn't seem to work anymore.

**Comment by trexminer** [comment] 2020-12-10 12:02
Try `--no-nvml`

**Comment by turbare** [comment] 2020-12-10 12:06
That worked, thanks!

**Comment by Kingdom256** [comment] 2020-12-10 16:39
> Try `--no-nvml`

this worked for me! thanks!

**Comment by kevduc** [comment] 2020-12-10 19:20
> Try `--no-nvml`

Nice, worked for me too! (I also updated to the 460.x drivers recently)  

For info --no-nvml just disables NVML GPU stats ([https://developer.nvidia.com/nvidia-management-library-nvml](https://developer.nvidia.com/nvidia-management-library-nvml))

**Comment by Kingdom256** [comment] 2020-12-11 03:19
> Tratar `--no-nvml`

Does this affect something? I think so!

**Comment by grs101** [comment] 2020-12-18 22:35
Need download NVIDIA GeForce 460.97 Hotfix
