### ISSUE TITLE
EVGA 3080 12GB does not recognize as LHR

### ISSUE THREAD

**Issue by GenCodeInc** [trexminer/T-Rex#1015] opened 2022-01-25 00:15 UTC
EVGA 3080 12GB does not recognize as LHR, trying to force LHR it never settles and mines much lower than without LHR mode.  EVGA GeForce RTX 3080 12GB FTW3 ULTRA GAMING, 12G-P5-4877-KL, 12GB GDDR6X, iCX3 Technology, ARGB LED, Metal Backplate, LHR

**Comment by rayven96** [comment] 2022-01-25 06:12
Same
Please FIX IT!!

**Comment by trexminer** [comment] 2022-01-25 06:41
Duplicate of https://github.com/trexminer/T-Rex/issues/996

**Closed by trexminer** 2022-01-25 06:41 UTC
