### ISSUE TITLE
Some error

### ISSUE THREAD

**Issue by lly007** [trexminer/T-Rex#296] opened 2021-03-15 11:45 UTC
T-Rex NVIDIA GPU miner v0.19.12  -  [CUDA v10.0 | Linux]
 r.34753df0aef5
 
 NVIDIA Driver v440.64.00
 CUDA devices available: 2
 
 WARN: DevFee 1% (ethash)
 
 URL : stratum+http://192.168.96.183:8080
 USER: 0x1f75eccd8fbddf057495b96669ac15f8e296c2cd
 PASS: x
 WRK : rig7
 
 Starting on: 192.168.96.183:8080
 Using protocol: stratum1.
 Start working in get-work mode...
 ApiServer: HTTP server started on 127.0.0.1:4067
 ---------------------------------------------------
 For control navigate to: http://127.0.0.1:4067/trex
 ---------------------------------------------------
 ApiServer: Telnet server started on 127.0.0.1:4068
 ethash epoch: 401, block: 12042936, diff: 4.00 G
 ethash epoch: 401, block: 12042936, diff: 4.00 G
 WARN: GPU #0(005e00): Tesla V100-PCIE-32GB, intensity set to 22 ... [LOW LOAD MODE]
 WARN: GPU #1(00d800): Tesla V100-PCIE-32GB, intensity set to 22 ... [LOW LOAD MODE]
 WARN: NVML: can't get fan speed for GPU #0, not supported
 WARN: NVML: can't get fan speed for GPU #1, not supported
 GPU #1: generating DAG 4.13 GB for epoch 401 ...
 GPU #0: generating DAG 4.13 GB for epoch 401 ...
GPU #1: DAG generated [crc: 38c9e44b, time: 2958 ms], memory left: 27.30 GB
GPU #0: DAG generated [crc: 38c9e44b, time: 2958 ms], memory left: 27.30 GB
 GPU #1: using kernel #3
 GPU #0: using kernel #3
 [ OK ] 1/1 - 0.00 H/s, 4ms ... GPU #1
 [ OK ] 2/2 - 179.59 MH/s, 4ms ... GPU #0
 ethash epoch: 401, block: 12042937, diff: 4.00 G
 ethash epoch: 401, block: 12042938, diff: 4.00 G
 [ OK ] 3/3 - 179.58 MH/s, 2ms ... GPU #0
 [ OK ] 4/4 - 179.58 MH/s, 5ms ... GPU #1
 ethash epoch: 401, block: 12042939, diff: 4.00 G
 [ OK ] 5/5 - 179.59 MH/s, 4ms ... GPU #1
 ethash epoch: 401, block: 12042940, diff: 4.00 G
 ethash epoch: 401, block: 12042941, diff: 4.00 G
 ethash epoch: 401, block: 12042942, diff: 4.00 G
 TREX: eyJhIjoiUEp5OHdZeWV3Sk83VEpkNFRoaHVEN3J1RWxXR1QzZTF1eGpWcDIvSFhQWHYreC9HTUdMU0hrVzc4UkxjYmY0OWZBQmdZZTJDVUJGQ2txTGpQQ1RkZUVGa0RzVS9yRG92cGg4T1FNaFE1Zk02TUNYa2hldWM1Rk9xVWNCMUtBSGxDMlFxRExpMFBPeEkzelZCTk9HTU9XSGVPdklZUFRMTWV3V2psYVlwaTVZeTFaV0hzcEUweWJPMC9mbnIwWjY5VE1xN1oycHBLMXkvcTFpRHo3N3lvbzdXbGJROUZJcG5ZV2hSbXhndGI2NXhmd3A1R1Vvd0VuUXRDdWpIM1NOciIsImIiOiJYazhUWGpsOXFwYzdxMzJwWlI1emVBPT0ifQo=
 WARN: Miner is going to shutdown...
 Main loop finished. Cleaning up resources...
 ApiServer: stopped listening on 127.0.0.1:4067
 ApiServer: stopped listening on 127.0.0.1:4068
 ethash epoch: 401, block: 12042943, diff: 4.00 G
 T-Rex finished.

**Comment by pdieppa** [comment] 2021-03-15 20:32
Have you tried a higher version of Nvidia drivers like 460.56?

**Comment by pc-2198x** [comment] 2021-03-15 22:01
> Have you tried a higher version of Nvidia drivers like 460.56?

I am experiencing the same issue, using Nvidia driver 460.56:

 T-Rex NVIDIA GPU miner v0.19.12  -  [CUDA v11.10 | Linux]
 r.34753df0aef5
 
 NVIDIA Driver v460.56
 CUDA devices available: 1
 
 WARN: DevFee 1% (ethash)
 
 URL : stratum+tcp://eu1.ethermine.org:4444
 USER: 0x1f75eccd8fbddf057495b96669ac15f8e296c2cd
 PASS: x
 WRK : rig0
 
 Starting on: eu1.ethermine.org:4444
 Using protocol: stratum1.
 Authorizing...
 Authorized successfully.
 ApiServer: HTTP server started on 127.0.0.1:4067
 ---------------------------------------------------
 For control navigate to: http://127.0.0.1:4067/trex
 ---------------------------------------------------
 ApiServer: Telnet server started on 127.0.0.1:4068
 ethash epoch: 401, block: 12045769, diff: 4.00 G
 ethash epoch: 401, block: 12045769, diff: 4.00 G
 WARN: GPU #0(000100): EVGA GeForce RTX 2080 Ti, intensity set to 22
 TREX: eyJhIjoidGdQWmJQTmZ3aEs3WXNpVDZKZlBHNGRuVldqY256c3d4VE9tN0lYK25ZVXhFODBEeWxzZXlDdGRyVEtlTTQyZjRWbk8xbEZPZXBmRmVpSXdCNWF6WXc3OGFVT0Y1dHRsczVSOGdQUTd5czg9IiwiYiI6IjQxaEt6ZDdMWlZ0OVM3WDZGcHBVc2c9PSJ9Cg==
 WARN: Miner is going to shutdown...
 Main loop finished. Cleaning up resources...
 ApiServer: stopped listening on 127.0.0.1:4067
 ApiServer: stopped listening on 127.0.0.1:4068
 GPU #0: generating DAG 4.13 GB for epoch 401 ...
 T-Rex finished.
./ETH-ethermine.sh: line 2:  4196 Killed                  ./t-rex -a ethash -o stratum+tcp://eu1.ethermine.org:4444 -u 0x1f75eccd8fbddf057495b96669ac15f8e296c2cd -p x -w rig0
[dmg@ARCH-TOWER t-rex-0.19.12-linux-cuda11.1]$

**Comment by Paranoid-Dev** [comment] 2021-03-16 06:56
Me too, Nvidia driver 460.56 on Arch Linux
All cuda versions fail

**Comment by sunaurus** [comment] 2021-03-16 07:56
Just to add to the previous comment, it was working fine up until the latest nvidia driver update on Arch Linux.

**Comment by sunaurus** [comment] 2021-03-16 16:15
Actually, it's probably caused by some other update, not the driver. I just tried with `linux-lts` and `nvidia-lts`, it still results in the same error. 

Is there any way to extract a useful error message out of this string? It looks like base64 encoded json, but the contents aren't very helpful:

```
{"a":"1vPPaefTK4zcqSv8TpqvBrd9AKYJgBIW2T8OhAB3CW/h6zfwmAhCYCMu/EnCumYj5KMTsbitK8DvsDIA0S+028klCqoEYUM1IdML3d4xLew=","b":"PmtFKDZ4wqnFDkqhqpRxLw=="}
```

**Comment by trexminer** [comment] 2021-03-16 17:08
Possible fix CUDA 10. Try please: https://www.dropbox.com/s/3hu7mdfljfx4ap0/t-rex-0.19.12-linux-cuda10.0.tar.gz?dl=1

**Comment by pc-2198x** [comment] 2021-03-16 18:23
> Possible fix CUDA 10. Try please: https://www.dropbox.com/s/3hu7mdfljfx4ap0/t-rex-0.19.12-linux-cuda10.0.tar.gz?dl=1

I can confirm this works.

**Comment by sebgab** [comment] 2021-03-16 19:31
> Possible fix CUDA 10. Try please: https://www.dropbox.com/s/3hu7mdfljfx4ap0/t-rex-0.19.12-linux-cuda10.0.tar.gz?dl=1

This solved the issue for me too.

**Comment by Paranoid-Dev** [comment] 2021-03-16 22:33
Solved for me as well

**Comment by Wulfre** [comment] 2021-03-17 04:13
Same error on latest 11.1 build.

```
 T-Rex NVIDIA GPU miner v0.19.12  -  [CUDA v11.10 | Linux]
 r.34753df0aef5

 NVIDIA Driver v460.56
 CUDA devices available: 1

 TREX: eyJhIjoia1VjQ1FvNXZ2bTZKbnFxbnRiNmxLZjE2L3BSbTh2NFhZZHYwZXptbXV0Sm91VTQvMTlqRDZOaDRNTlBoSzNoMnhlTlFvbFZ2dGh5UTZPZFF2UEJWVzI2SzhsRFVWcjRYbFVJNWF6anJmVjQ9IiwiYiI6IkQ2ZnBYRTB3OFZidWl4dGt5V2tSQlE9PSJ9Cg==

```

**Comment by sniperlucian** [comment] 2021-03-18 17:33
can we have a possible fix for Cuda 11 too please ;)

**Comment by trexminer** [comment] 2021-03-19 08:38
> can we have a possible fix for Cuda 11 too please ;)

https://www.dropbox.com/s/yiy5gq26ownzp01/t-rex-0.19.12-new-linux-cuda11.1.tar.gz?dl=1

**Comment by pc-2198x** [comment] 2021-03-19 20:25
> > can we have a possible fix for Cuda 11 too please ;)
> 
> https://www.dropbox.com/s/yiy5gq26ownzp01/t-rex-0.19.12-new-linux-cuda11.1.tar.gz?dl=1

Can confirm this works with the new 460.67 Nvidia driver and Cuda 11.2. Thank you for the fix.

**Comment by gandroz** [comment] 2021-03-19 21:00
Cuda 11.0 & driver 460.32.03 on ubuntu does not work

**Comment by deeperarcher** [comment] 2021-03-24 16:27
> > can we have a possible fix for Cuda 11 too please ;)
> 
> https://www.dropbox.com/s/yiy5gq26ownzp01/t-rex-0.19.12-new-linux-cuda11.1.tar.gz?dl=1

Worked for me after the newest Manjaro update broke it. Had to use the Cuda 11.1  because the 10.0 wasn't supported by my 3070.

Thanks for the fix.

**Comment by noozo** [comment] 2021-03-25 16:09
Manjaro broke it indeed. Confirmed to be working.

**Comment by gandroz** [comment] 2021-03-25 17:13
![image](https://user-images.githubusercontent.com/38106881/112514633-e51f8f80-8d6b-11eb-9408-03eace005ddd.png)

**Comment by gandroz** [comment] 2021-03-25 17:15
![image](https://user-images.githubusercontent.com/38106881/112514897-29129480-8d6c-11eb-936a-fd49dfdb4537.png)

**Comment by trexminer** [comment] 2021-11-19 14:08
Should be fixed in the newest version

**Closed by trexminer** 2021-11-19 14:08 UTC
