### ISSUE TITLE
I hope trex miner supports toncoin and all their coin pools.

### ISSUE THREAD

**Issue by GminerManiac** [trexminer/T-Rex#1140] opened 2022-02-27 19:03 UTC
I hope trex miner supports toncoin and all their coin pools.

Can you make eth + ton dual miner? I hope you add the function for next version.

**Comment by trexminer** [comment] 2022-02-28 12:47
Duplicate of https://github.com/trexminer/T-Rex/issues/1035

**Closed by trexminer** 2022-02-28 12:47 UTC
