### ISSUE TITLE
[0.24.7] Miner does not create log files

### ISSUE THREAD

**Issue by cutestor1** [trexminer/T-Rex#900] opened 2021-12-01 18:16 UTC
로그 기록이 남지 않습니다.

**Comment by trexminer** [comment] 2021-12-02 03:33
Thanks for reporting. It's a known issue and will be fixed in the next version.

**Comment by trexminer** [comment] 2021-12-02 03:34
Duplicate of https://github.com/trexminer/T-Rex/issues/832

**Closed by trexminer** 2021-12-02 03:34 UTC
