### ISSUE TITLE
Flux

### ISSUE THREAD

**Issue by JackDeRke** [trexminer/T-Rex#1182] opened 2022-03-24 12:22 UTC
Just thinking if I have just not found it or if Flux isn´t supported. Would certainly be nice to be prepared for it. Or is there a reason it isn´t there yet.
Thanks :)

**Comment by trexminer** [comment] 2022-03-24 12:52
Duplicate of https://github.com/trexminer/T-Rex/issues/895

**Closed by trexminer** 2022-03-24 12:52 UTC
