### ISSUE TITLE
add fan control in linux

### ISSUE THREAD

**Issue by webprodesign1** [trexminer/T-Rex#1043] opened 2022-02-04 21:51 UTC
Adding fan control in linux would help put a limit on each gpu. It is very useful in countries where it is very hot

**Comment by mcwillzz** [comment] 2022-02-08 10:48
+1 would like to see fan control implemented in linux as well!

**Comment by trexminer** [comment] 2022-02-09 15:24
Duplicate of https://github.com/trexminer/T-Rex/issues/592

**Closed by trexminer** 2022-02-09 15:24 UTC
