### ISSUE TITLE
Abouth WARN: NVML: can't get GPU #?, error code 999 

### ISSUE THREAD

**Issue by DnzYg** [trexminer/T-Rex#573] opened 2021-08-14 08:05 UTC
I am running t-rex with different settings in two cmd windows on the same windows 10 pc.

When one of the gpu card crashes, the t-rex running independently in the other cmd window continues to run, but gets the Warning message "WARN: NVML: can't get GPU #..., error code 999 " and cannot get the power and fan values.

![T-Rex Issue Capture](https://user-images.githubusercontent.com/88924605/129439879-25581fe1-6daa-4409-bad8-9efe41a77ecb.JPG)

**Comment by trexminer** [comment] 2021-08-14 11:35
Duplicate of https://github.com/trexminer/T-Rex/issues/226

**Closed by trexminer** 2021-08-14 11:35 UTC
