### ISSUE TITLE
x16rt? Avian

### ISSUE THREAD

**Issue by PSLLSP** [trexminer/T-Rex#1054] opened 2022-02-07 09:06 UTC
`T-Rex` miner supported algo **x16rt** in the past but that algo was removed in version 0.20.0, **x16rt** was not popular algo few months ago. Situation changed when **Avian (AVN)** coin was launched at the end of 2021. It is interesting to see that [T-Rex 0.19.14](https://github.com/trexminer/T-Rex/releases/tag/0.19.14) is the most popular miner for NVIDIA GPUs at **zergpool**: https://zergpool.com/site/miners?algo=x16rt

What about an idea to add support for **x16rt** to the latest T-Rex?? I was mining **x16rt** with `WildRig-multi` miner for few days but I just found that older T-Rex is much better for Avian coin...

**Comment by SoulRipper888** [comment] 2022-02-07 15:06
Same here... Hashrate is almost double compared to WildRig on my 3080.
v0.19.14 works, but I miss a few settings like pl, core, mem.

**Comment by trexminer** [comment] 2022-02-11 08:01
Duplicate of https://github.com/trexminer/T-Rex/issues/622

**Closed by trexminer** 2022-02-11 08:01 UTC
