### ISSUE TITLE
WARN: NML: can't get fan speed for GPU #X, error code 999

### ISSUE THREAD

**Issue by pberetta** [trexminer/T-Rex#491] opened 2021-04-30 15:19 UTC
Hello trexminer team,

I'm facing an issue with a RTX 3080, where as soon as I open the miner, I receive the following warning:

WARN: NML: can't get fan speed for GPU #X, error code 999

Then, the rig crashes a moment later. 

I tested the GPU alone and with its peers, and I got the same result on both scenarios. I attached the pictures of both scenarios.
![T-Rex 20 3 RTX 3080 5GPUs](https://user-images.githubusercontent.com/83380178/116716488-6e466980-a99d-11eb-82d9-34ca85ab4468.PNG)
![T-Rex 20 3 RTX3080 Crashes Investigation](https://user-images.githubusercontent.com/83380178/116716490-6edf0000-a99d-11eb-9b2b-996bad77e82b.PNG)

If you could provide me with a feedback, I'd appreciate it.

**Comment by pberetta** [comment] 2021-04-30 17:46
#LOGGING

20210430 11:56:40 T-Rex NVIDIA GPU miner v0.20.3  -  [Windows]
20210430 11:56:40 r.555472ba6b21
20210430 11:56:40 
20210430 11:56:40 NVIDIA Driver v460.89
20210430 11:56:40 CUDA devices available: 5
20210430 11:56:40 
20210430 11:56:40 WARN: DevFee 1% (ethash)
20210430 11:56:40 
20210430 11:56:40 URL : stratum+ssl://eth-us-east.flexpool.io:5555
20210430 11:56:40 USER: 0x6f744ac1551818e91ccbf4c5038b551614556e55
20210430 11:56:40 PASS: x
20210430 11:56:40 WRK : 3080_rig
20210430 11:56:40 
20210430 11:56:40 Starting on: eth-us-east.flexpool.io:5555
20210430 11:56:40 WARN: unknown vendor id 0x103c of GPU nvml_id=#0
20210430 11:56:40 Using protocol: stratum1.
20210430 11:56:40 Authorizing...
20210430 11:56:40 Authorized successfully.
20210430 11:56:40 ethash epoch: 411, block: 12343039, diff: 4.00 G
20210430 11:56:40 ethash epoch: 411, block: 12343039, diff: 4.00 G
20210430 11:56:40 ApiServer: HTTP server started on 127.0.0.1:4067
20210430 11:56:40 ---------------------------------------------------
20210430 11:56:40 For control navigate to: http://127.0.0.1:4067/trex
20210430 11:56:40 ---------------------------------------------------
20210430 11:56:40 ApiServer: Telnet server started on 127.0.0.1:4068
20210430 11:56:41 WARN: GPU #0(000100): GeForce RTX 3080, intensity 22
20210430 11:56:41 WARN: GPU #1(000200): Gigabyte GeForce RTX 3080, intensity 22
20210430 11:56:41 ethash epoch: 411, block: 12343040, diff: 4.00 G
20210430 11:56:41 WARN: GPU #2(000400): Dell GeForce RTX 3080, intensity 22
20210430 11:56:41 WARN: GPU #3(000500): Dell GeForce RTX 3080, intensity 22
20210430 11:56:42 WARN: GPU #4(000600): Gigabyte GeForce RTX 3080, intensity 22
20210430 11:56:45 GPU #2: generating DAG 4.21 GB for epoch 411 ...
20210430 11:56:45 GPU #1: generating DAG 4.21 GB for epoch 411 ...
20210430 11:56:45 GPU #0: generating DAG 4.21 GB for epoch 411 ...
20210430 11:56:45 GPU #4: generating DAG 4.21 GB for epoch 411 ...
20210430 11:56:45 GPU #3: generating DAG 4.21 GB for epoch 411 ...
20210430 11:56:49 ethash epoch: 411, block: 12343041, diff: 4.00 G
20210430 11:56:51 GPU #4: DAG generated [crc: a895d4ae, time: 6553 ms], memory left: 4.68 GB
20210430 11:56:51 GPU #1: DAG generated [crc: a895d4ae, time: 6799 ms], memory left: 4.68 GB
20210430 11:56:52 GPU #2: DAG generated [crc: a895d4ae, time: 7076 ms], memory left: 4.68 GB
20210430 11:56:52 GPU #0: DAG generated [crc: a895d4ae, time: 7319 ms], memory left: 4.68 GB
20210430 11:56:52 GPU #3: DAG generated [crc: a895d4ae, time: 7597 ms], memory left: 4.68 GB
20210430 11:57:02 ethash epoch: 411, block: 12343042, diff: 4.00 G
20210430 11:57:06 ethash epoch: 411, block: 12343043, diff: 4.00 G
20210430 11:57:06 GPU #4: using kernel #4
20210430 11:57:07 ethash epoch: 411, block: 12343044, diff: 4.00 G
20210430 11:57:07 GPU #1: using kernel #4
20210430 11:57:07 GPU #2: using kernel #4
20210430 11:57:07 GPU #0: using kernel #4
20210430 11:57:08 GPU #3: using kernel #4
20210430 11:57:20 ethash epoch: 411, block: 12343045, diff: 4.00 G
20210430 11:57:23 ethash epoch: 411, block: 12343046, diff: 4.00 G
20210430 11:57:35 [ OK ] 1/1 - 501.39 MH/s, 62ms ... GPU #2
20210430 11:57:35 [ OK ] 2/2 - 501.39 MH/s, 62ms ... GPU #1
20210430 11:57:37 [ OK ] 3/3 - 501.47 MH/s, 62ms ... GPU #3
20210430 11:57:37 ethash epoch: 411, block: 12343047, diff: 4.00 G
20210430 11:57:42 [ OK ] 4/4 - 501.22 MH/s, 47ms ... GPU #3
20210430 11:57:43 ethash epoch: 411, block: 12343048, diff: 4.00 G

-----------------20210430 11:57:51 -----------------
Mining at eth-us-east.flexpool.io:5555, diff: 4.00 G
GPU #0: RTX 3080          - 100.33 MH/s, [T:41C, P:223W, F:100%, E:464kH/W]
GPU #1: Gigabyte RTX 3080 - 100.58 MH/s, [T:38C, P:237W, F:100%, E:435kH/W], 1/1 R:0%
GPU #2: Dell RTX 3080     - 100.41 MH/s, [T:38C, P:223W, F: 95%, E:467kH/W], 1/1 R:0%
GPU #3: Dell RTX 3080     -  99.45 MH/s, [T:45C, P:223W, F:100%, E:458kH/W], 2/2 R:0%
GPU #4: Gigabyte RTX 3080 - 100.10 MH/s, [T:37C, P:237W, F:100%, E:430kH/W]
Hashrate: 500.88 MH/s, Shares/min: 22.857 (Avr. 3.834), Avr.P: 1112W, Avr.E: 450kH/W
Uptime: 1 min 11 secs | Algo: ethash | T-Rex v0.20.3
WD: 1 min 15 secs, shares: 4/4 

20210430 11:57:54 [ OK ] 5/5 - 500.92 MH/s, 47ms ... GPU #3
20210430 11:58:08 [ OK ] 6/6 - 500.57 MH/s, 47ms ... GPU #2
20210430 11:58:13 ethash epoch: 411, block: 12343049, diff: 4.00 G
20210430 11:58:15 [ OK ] 7/7 - 500.33 MH/s, 47ms ... GPU #4
20210430 11:58:19 [ OK ] 8/8 - 500.28 MH/s, 47ms ... GPU #1

-----------------20210430 11:58:21 -----------------
Mining at eth-us-east.flexpool.io:5555, diff: 4.00 G
GPU #0: RTX 3080          - 100.21 MH/s, [T:43C, P:223W, F:100%, E:449kH/W]
GPU #1: Gigabyte RTX 3080 - 100.63 MH/s, [T:40C, P:237W, F:100%, E:425kH/W], 2/2 R:0%
GPU #2: Dell RTX 3080     - 100.42 MH/s, [T:39C, P:223W, F: 96%, E:450kH/W], 2/2 R:0%
GPU #3: Dell RTX 3080     -  98.77 MH/s, [T:47C, P:223W, F: 99%, E:443kH/W], 3/3 R:0%
GPU #4: Gigabyte RTX 3080 - 100.23 MH/s, [T:39C, P:237W, F:100%, E:423kH/W], 1/1 R:0%
Hashrate: 500.26 MH/s, Shares/min: 9.51 (Avr. 4.854), Avr.P: 1143W, Avr.E: 438kH/W
Uptime: 1 min 41 secs | Algo: ethash | T-Rex v0.20.3
WD: 1 min 45 secs, shares: 8/8 

20210430 11:58:23 [ OK ] 9/9 - 500.26 MH/s, 125ms ... GPU #4
20210430 11:58:26 [ OK ] 10/10 - 500.13 MH/s, 78ms ... GPU #1
20210430 11:58:26 [ OK ] 11/11 - 500.13 MH/s, 47ms ... GPU #3
20210430 11:58:32 [ OK ] 12/12 - 500.09 MH/s, 47ms ... GPU #4
20210430 11:58:32 [ OK ] 13/13 - 500.09 MH/s, 63ms ... GPU #2
20210430 11:58:34 [ OK ] 14/14 - 499.83 MH/s, 63ms ... GPU #4
20210430 11:58:38 ethash epoch: 411, block: 12343050, diff: 4.00 G
20210430 11:58:40 [ OK ] 15/15 - 499.63 MH/s, 62ms ... GPU #1

-----------------20210430 11:58:51 -----------------
Mining at eth-us-east.flexpool.io:5555, diff: 4.00 G
GPU #0: RTX 3080          - 100.11 MH/s, [T:44C, P:223W, F:100%, E:449kH/W]
GPU #1: Gigabyte RTX 3080 - 100.65 MH/s, [T:42C, P:237W, F:100%, E:425kH/W], 4/4 R:0%
GPU #2: Dell RTX 3080     - 100.17 MH/s, [T:40C, P:223W, F: 96%, E:449kH/W], 3/3 R:0%
GPU #3: Dell RTX 3080     -  97.97 MH/s, [T:49C, P:223W, F:100%, E:439kH/W], 4/4 R:0%
GPU #4: Gigabyte RTX 3080 - 100.48 MH/s, [T:40C, P:237W, F:100%, E:424kH/W], 4/4 R:0%
Hashrate: 499.38 MH/s, Shares/min: 12.893 (Avr. 7.508), Avr.P: 1143W, Avr.E: 437kH/W
Uptime: 2 mins 11 secs | Algo: ethash | T-Rex v0.20.3
WD: 2 mins 15 secs, shares: 15/15 

20210430 11:58:56 ethash epoch: 411, block: 12343051, diff: 4.00 G
20210430 11:59:04 [ OK ] 16/16 - 499.05 MH/s, 63ms ... GPU #2
20210430 11:59:16 WARN: NVML: can't get fan speed for GPU #4, error code 999

-----------------20210430 11:59:22 -----------------
Mining at eth-us-east.flexpool.io:5555, diff: 4.00 G
GPU #0: RTX 3080          -  99.71 MH/s, [T:45C, P:227W, F:100%, E:447kH/W]
GPU #1: Gigabyte RTX 3080 - 100.37 MH/s, [T:43C, P:237W, F:100%, E:423kH/W], 4/4 R:0%
GPU #2: Dell RTX 3080     -  99.08 MH/s, [T:40C, P:221W, F: 95%, E:446kH/W], 4/4 R:0%
GPU #3: Dell RTX 3080     -  97.28 MH/s, [T:50C, P:222W, F: 99%, E:438kH/W], 4/4 R:0%
GPU #4: Gigabyte RTX 3080 - 100.63 MH/s, [T:36C, P:237W, E:425kH/W], 4/4 R:0%
Hashrate: 497.06 MH/s, Shares/min: 10.103 (Avr. 6.676), Avr.P: 1141W, Avr.E: 436kH/W
Uptime: 2 mins 43 secs | Algo: ethash | T-Rex v0.20.3
WD: 2 mins 47 secs, shares: 16/16 

20210430 11:59:35 ethash epoch: 411, block: 12343052, diff: 4.00 G
20210430 11:59:43 ethash epoch: 411, block: 12343053, diff: 4.00 G
20210430 11:59:44 WARN: GPU #4: Gigabyte GeForce RTX 3080 is idle, last activity was 34 secs ago
20210430 11:59:44 ethash epoch: 411, block: 12343054, diff: 4.00 G
20210430 11:59:48 [ OK ] 17/17 - 491.29 MH/s, 47ms ... GPU #1
20210430 11:59:49 WARN: GPU #4: Gigabyte GeForce RTX 3080 is idle, last activity was 39 secs ago
20210430 11:59:52 ethash epoch: 411, block: 12343055, diff: 4.00 G

-----------------20210430 11:59:53 -----------------
Mining at eth-us-east.flexpool.io:5555, diff: 4.00 G
GPU #0: RTX 3080          -  98.28 MH/s, [T:45C, P:223W, F:100%, E:453kH/W]
GPU #1: Gigabyte RTX 3080 -  99.27 MH/s, [T:43C, P:237W, F:100%, E:435kH/W], 5/5 R:0%
GPU #2: Dell RTX 3080     -  97.65 MH/s, [T:40C, P:223W, F: 96%, E:456kH/W], 4/4 R:0%
GPU #3: Dell RTX 3080     -  95.96 MH/s, [T:51C, P:223W, F: 99%, E:448kH/W], 4/4 R:0%
GPU #4: Gigabyte RTX 3080 - 100.64 MH/s, 4/4 R:0%
Hashrate: 491.80 MH/s, Shares/min: 7.217 (Avr. 5.433)
Uptime: 3 mins 13 secs | Algo: ethash | T-Rex v0.20.3
WD: 3 mins 17 secs, shares: 17/17 

20210430 11:59:54 WARN: GPU #4: Gigabyte GeForce RTX 3080 is idle, last activity was 44 secs ago
20210430 11:59:57 [ OK ] 18/18 - 492.10 MH/s, 47ms ... GPU #1
20210430 11:59:59 WARN: GPU #4: Gigabyte GeForce RTX 3080 is idle, last activity was 49 secs ago
20210430 12:00:04 WARN: GPU #4: Gigabyte GeForce RTX 3080 is idle, last activity was 54 secs ago

**Comment by trexminer** [comment] 2021-05-02 01:18
Duplicate of https://github.com/trexminer/T-Rex/issues/226

**Closed by trexminer** 2021-05-02 01:18 UTC

**Comment by nebulaEXE** [comment] 2021-11-11 16:32
@pberetta

Did you ever fix this issue? I'm encountering similar behavior from a Ventus 3080 that used to run fine.

**Comment by dimitriovic** [comment] 2022-01-03 01:59
> @pberetta
> 
> Did you ever fix this issue? I'm encountering similar behavior from a Ventus 3080 that used to run fine.

i found out by checking bios setting that csm support was enabled. by disabling it, the error stopped. so in my case it was the solution.
