### ISSUE TITLE
Problem with GTX 980 TI

### ISSUE THREAD

**Issue by hRo-ICE** [trexminer/T-Rex#248] opened 2021-02-25 13:18 UTC
Hello,

I want to use the T-Rex Minier but its doesn't work.

Error is:

20210225 14:17:31 TREX: Can't find nonce with device [ID=0, GPU #0], cuda exception in [Ethash::benchmark_kernel, 61], the launch timed out and was terminated, try to reduce overclock to stabilize GPU state

can you help me?

Greeting hRo-ICE

**Comment by realuser** [comment] 2021-03-03 04:39
I also get the same error with a GTX 970 (4GB).  On the other hand my GTX 1070 (8GB) on the same system does seem to work.  I'm trying to use the `etchash` algorithm

```
TREX: Can't find nonce with device [ID=0, GPU #1], cuda exception in [Ethash::benchmark_kernel, 61],
the launch timed out and was terminated, try to reduce overclock to stabilize GPU state
WARN: Miner is going to shutdown...
Main loop finished. Cleaning up resources...
ApiServer: stopped listening on 127.0.0.1:4067
ApiServer: stopped listening on 127.0.0.1:4068
T-Rex finished.
```

I'm using `t-rex-0.19.11-win-cuda11.1`. I have not tried to overclock anything and am just using standard settings

**Comment by realuser** [comment] 2021-03-03 04:44
@hRo-ICE this seemed to fix it for me: https://github.com/trexminer/T-Rex/issues/153#issuecomment-774802857

**Comment by trexminer** [comment] 2021-03-04 08:13
Duplicate of #153

**Closed by trexminer** 2021-03-04 08:13 UTC
