### ISSUE TITLE
Error 999

### ISSUE THREAD

**Issue by coinboy368** [trexminer/T-Rex#345] opened 2021-03-26 21:05 UTC
![Screenshot_20210326-153329_Gallery](https://user-images.githubusercontent.com/81441811/112692287-10ca7480-8e55-11eb-8294-05d42d1ae691.jpg)
 

I keep getting this hr sometimes after hrs sometimes days

**Comment by trexminer** [comment] 2021-04-16 01:40
Duplicate of https://github.com/trexminer/T-Rex/issues/226

**Closed by trexminer** 2021-04-16 01:40 UTC
