### ISSUE TITLE
--pl always generates an error

### ISSUE THREAD

**Issue by Externinator** [trexminer/T-Rex#608] opened 2021-09-06 17:51 UTC
Whenever I set --pl, it says WARN: Can't setup power limit for [000100]: value out of range [0%, 0%].

I am using v0.21.6.

**Comment by trexminer** [comment] 2021-09-07 08:52
Duplicate of https://github.com/trexminer/T-Rex/issues/499

**Closed by trexminer** 2021-09-07 08:52 UTC
