### ISSUE TITLE
lhr-low-power by card 

### ISSUE THREAD

**Issue by dedizones** [trexminer/T-Rex#958] opened 2021-12-23 18:38 UTC
Hello,

I use the lhr-low-power mode for my LHR cards, I gain 300w for barely 40MH of loss so more advantageous for me watt vs MHs

but I would like from now on activated the lhr-low-power mode by card

example :

"lhr-low-power": "1,1,0,0,0,0"

1 = True / enabled
0 = false / disabled

Knowing that 1 = 68 / low mode power and that 0 = 74 / normal mode power

Is it possible to do that?

I ask because my 3080Ti on ETH consumes a lot of energy despite 91MHs for 280W (EVGA and MSI) but I have 3070Ti which does not consume much and are at 61Mhs for 165w, I will just limit the watt a little via the lhr-low-power

**Comment by trexminer** [comment] 2021-12-27 05:52
Duplicate of https://github.com/trexminer/T-Rex/issues/840

**Closed by trexminer** 2021-12-27 05:52 UTC
