### ISSUE TITLE
Web Page not working with Chrome.

### ISSUE THREAD

**Issue by LupoCri** [trexminer/T-Rex#818] opened 2021-11-11 13:05 UTC
Hi.

After update to 0.24.6, web page stop working (blank page) only on Chrome browser. Mozilla still working... 
Cache cleared. Tryed with Chrome browser on Ubuntu20.04 & Win10, T-Rex run on Win10. 

Tnx for all.

LupoCri.

**Comment by trexminer** [comment] 2021-11-12 01:51
Thanks for reporting, I confirm it's a bug and we'll fix it in the next version. Temporary solution is to delete browser cookies or use a different browser.

**Comment by Marsi4eg** [comment] 2021-11-12 11:00
I'd like to add that web page became very laggy, mostly when graph is enabled. Pressing something on the page takes effect only after 3-5 seconds. Firefox 94.0.1.

**Comment by trexminer** [comment] 2021-11-12 11:33
> I'd like to add that web page became very laggy, mostly when graph is enabled. Pressing something on the page takes effect only after 3-5 seconds. Firefox 94.0.1.

Could you please write here your PC hardware configuration where you open the browser with trex webui?

**Comment by Marsi4eg** [comment] 2021-11-12 11:47
One with Core2Quad Q9650, 8gb ram, another with i5-3570k, 16gb ram.
Seems like webui hangs for a few seconds in the moment of graph update. Same happens when checking/unchecking checkboxes below the graph (probably because they force graph to be re-drawn).

There wasn't such behavior in 0.24.5, graph updates immidiately in it.

**Comment by trexminer** [comment] 2021-11-12 11:50
> One with Core2Quad Q9650, 8gb ram, another with i5-3570k, 16gb ram. Seems like webui hangs for a few seconds in the moment of graph update. Same happens when checking/unchecking checkboxes below the graph (probably because they force graph to be re-drawn).
> 
> There wasn't such behavior in 0.24.5, graph updates immidiately in it.

Do you see hangs in case of graph hide?

**Comment by Marsi4eg** [comment] 2021-11-12 12:04
With hidden graph everything looks OK. The page still hangs for a half second on update though (can be reproduced when you try to continuously select text on the page with mouse in the moment of update), but I think it's absolutely normal behavior. Seems like only graph is kinda heavy now

**Comment by LupoCri** [comment] 2021-11-12 12:26
I also confirm the hangs issue with graph enabled. same setup as @Marsi4eg.

**Comment by trexminer** [comment] 2021-11-12 17:20
@Marsi4eg @LupoCri could you please try this webui assembly?
[webui.zip](https://github.com/trexminer/T-Rex/files/7529278/webui.zip)
 
Put it into your miner folder and restart the miner. Should work faster on big data.

**Comment by LupoCri** [comment] 2021-11-12 17:34
Patch applied. I have to wait for 24 hours of data?

LC

**Comment by trexminer** [comment] 2021-11-12 17:41
@LupoCri  Till the time you got hang issue.

**Comment by Marsi4eg** [comment] 2021-11-13 11:11
Installed hotfix, Just after start and a couple of hours after - it works perfectly, but now after 14+ hours it hangs on graph update again. I think it's caused by bigger amount of data that is being stored for the whole day (24h) but in older version it was only 2h max. Maybe it will be good to have some command line argument, like how much graph data to store - 2h or 24h. 

It wouldn't look so bad, if every graph update didn't load CPU by 25% everytime for a few seconds, even if the tab is inactive. So continuous monitoring causes more stress to CPU.

**Comment by trexminer** [comment] 2021-11-13 11:17
@Marsi4eg Thanks, we managed to reproduce it. There's another optimisation in 0.24.7 that we just released, so hopefully it should fix this for you. Please let me know how the page behaves with the newest version (don't forget to refresh the page with Ctrl+F5 to clean the cache). I'll leave the issue open, waiting for your feedback.

**Comment by LupoCri** [comment] 2021-11-13 11:24
Unfortunately I was unable to verify the issue due to the failed autoupdate. 
Until a couple of hours ago (about 12) everything was fine. 
I'll check later.
LC

**Comment by Marsi4eg** [comment] 2021-11-13 21:53
> 
> 
> @Marsi4eg Thanks, we managed to reproduce it. There's another optimisation in 0.24.7 that we just released, so hopefully it should fix this for you. Please let me know how the page behaves with the newest version (don't forget to refresh the page with Ctrl+F5 to clean the cache). I'll leave the issue open, waiting for your feedback.

10 hours and 25 min after update to 0.24.7, the page doesn't hang no more indeed! And doesn't cause cpu stress. 

BUT the hashrate axis scale seems to be broken now. Its lower value is always 0, but in older versions it was zoomed in to values near average. I mean for example if you have a hashrate around 32.5-32.7 mh - the axis had lower value of 28 and higher of 36, and you could see detailed hashrate line between this values. Now lower is always 0, and higher is 36 in this case. And the line looks always straight.

**Comment by trexminer** [comment] 2021-11-14 01:22
Thanks! Yes, I confirm it's broken, we'll be fixing it soon.

**Comment by LupoCri** [comment] 2021-11-14 11:12
Hi/all.
For me, after 24 hours the issue of the hang seems to be solved. 
Remains the issue of the wrong axis scale.
Thanks for all,
LC

**Comment by trexminer** [comment] 2021-12-10 09:16
Fixed in 0.24.8

**Closed by trexminer** 2021-12-10 09:16 UTC
