### ISSUE TITLE
Feature Requiest

### ISSUE THREAD

**Issue by mtmtmt123** [trexminer/T-Rex#891] opened 2021-11-28 14:13 UTC
Hello, T-Rex Developer
Can you add Heavyhash and Dualmining with heavyhash?
this is a big thing mining this 2 coins
thanks
@trexminer

**Comment by trexminer** [comment] 2021-11-28 14:14
Duplicate of https://github.com/trexminer/T-Rex/issues/860

**Closed by trexminer** 2021-11-28 14:14 UTC
