### ISSUE TITLE
Huh

### ISSUE THREAD

**Issue by galaxy4627** [trexminer/T-Rex#1113] opened 2022-02-21 17:21 UTC
So.. I'm mining to Sepholia Testnet running latest geth and when it's trying to submit the hashrate I keep getting this `WARN [02-21|12:17:21.821] Served eth_submitHashrate                conn=192.168.50.194:47352 reqid=9 duration="27.878µs" err="invalid argument 0: json: cannot unmarshal hex number with leading zero digits into Go value of type hexutil.Uint64"
` Yes, I'm using T-rex v0.25.8

**Comment by trexminer** [comment] 2022-02-28 12:42
Duplicate of https://github.com/trexminer/T-Rex/issues/1041

**Closed by trexminer** 2022-02-28 12:42 UTC
