### ISSUE TITLE
Appeare ”WARN: Can't setup fan speed for [000200]: NVAPI_NVIDIA_DEVICE_NOT_FOUND, code -6", then stop working

### ISSUE THREAD

**Issue by ch3nyy** [trexminer/T-Rex#1002] opened 2022-01-17 17:56 UTC
My graphics card: 3060Ti
System: Windows 10
NVIDIA Driver v457.85

Problem: After starting the software, it started to work normally, after a while appeare ”WARN: Can't setup fan speed for [000200]: NVAPI_NVIDIA_DEVICE_NOT_FOUND, code -6", then stop working.
After exiting the software, I found that the graphics card driver disappeared. Open the software again appears “ERROR: Can't start miner, can't initialize CUDA engine, cuda exception: CUDA_ERROR_NO_DEVICE. Is NVIDIA driver installed? ”
then reboot the system, back to the beginning.
Can someone help? Thanks!

log:
20220117 23:50:38 T-Rex NVIDIA GPU miner v0.21.6  -  [Windows]
20220117 23:50:38 r.3ea03a096378
20220117 23:50:38 
20220117 23:50:38 NVIDIA Driver v457.85
20220117 23:50:38 CUDA devices available: 1
20220117 23:50:38 
20220117 23:50:38 WARN: DevFee 1% (ethash)
20220117 23:50:38 
20220117 23:50:38 URL : stratum+ssl://us1.ethermine.org:5555
20220117 23:50:38 USER: 
20220117 23:50:38 PASS: x
20220117 23:50:38 WRK : 
20220117 23:50:38 
20220117 23:50:38 WARN: Temperature limit is activated. Limit is set to 75C.
20220117 23:50:38 
20220117 23:50:39 Starting on: us1.ethermine.org:5555
20220117 23:50:39 Using protocol: stratum1.
20220117 23:50:39 Authorizing...
20220117 23:50:39 Authorized successfully.
20220117 23:50:39 ApiServer: HTTP server started on 0.0.0.0:4067
20220117 23:50:39 -------------------------------------------------------
20220117 23:50:39 For control navigate to: http://192.168.6.126:4067/trex
20220117 23:50:39 -------------------------------------------------------
20220117 23:50:40 GPU #0(000200): MSI GeForce RTX 3060 Ti, intensity 22, fan 70%, mclock 1150MHz, pl 65%
20220117 23:50:40 ethash epoch: 467, block: 14023918, diff: 4.29 G
20220117 23:50:44 GPU #0: generating DAG 4.65 GB for epoch 467 ...
20220117 23:50:48 ethash epoch: 467, block: 14023919, diff: 4.29 G
20220117 23:50:53 ethash epoch: 467, block: 14023920, diff: 4.29 G
20220117 23:50:57 GPU #0: DAG generated [crc: 5016976d, time: 12836 ms], memory left: 1.91 GB
20220117 23:51:05 ethash epoch: 467, block: 14023921, diff: 4.29 G
20220117 23:51:05 ethash epoch: 467, block: 14023922, diff: 4.29 G
20220117 23:51:07 ethash epoch: 467, block: 14023923, diff: 4.29 G
20220117 23:51:13 GPU #0: using kernel #4
20220117 23:51:17 ethash epoch: 467, block: 14023924, diff: 4.29 G
20220117 23:51:22 ethash epoch: 467, block: 14023925, diff: 4.29 G
20220117 23:51:24 ethash epoch: 467, block: 14023926, diff: 4.29 G
20220117 23:51:30 ethash epoch: 467, block: 14023927, diff: 4.29 G

------------20220117 23:51:39 -------------
Mining at us1.ethermine.org:5555, diff: 4.29 G
GPU #0: MSI RTX 3060 Ti - 61.19 MH/s, [T:35C, P:129W, F:70%, E:537kH/W]
Shares/min: 0
Uptime: 1 min | Algo: ethash | T-Rex v0.21.6

20220117 23:51:51 ethash epoch: 467, block: 14023928, diff: 4.29 G
20220117 23:51:58 ethash epoch: 467, block: 14023929, diff: 4.29 G

------------20220117 23:52:09 -------------
Mining at us1.ethermine.org:5555, diff: 4.29 G
GPU #0: MSI RTX 3060 Ti - 61.19 MH/s, [T:36C, P:129W, F:70%, E:474kH/W]
Shares/min: 0
Uptime: 1 min 30 secs | Algo: ethash | T-Rex v0.21.6

20220117 23:52:09 ethash epoch: 467, block: 14023930, diff: 4.29 G
20220117 23:52:27 [ OK ] 1/1 - 61.20 MH/s, 27ms ... GPU #0
20220117 23:52:33 ethash epoch: 467, block: 14023931, diff: 4.29 G

------------20220117 23:52:39 -------------
Mining at us1.ethermine.org:5555, diff: 4.29 G
GPU #0: MSI RTX 3060 Ti - 61.20 MH/s, [T:36C, P:129W, F:70%, E:474kH/W], 1/1 R:0%
Shares/min: 1 (Avr. 0.556)
Uptime: 2 mins | Algo: ethash | T-Rex v0.21.6
WD: 2 mins 3 secs, shares: 1/1 

20220117 23:52:40 ethash epoch: 467, block: 14023932, diff: 4.29 G
20220117 23:52:47 ethash epoch: 467, block: 14023933, diff: 4.29 G
20220117 23:52:52 ethash epoch: 467, block: 14023934, diff: 4.29 G

------------20220117 23:53:09 -------------
Mining at us1.ethermine.org:5555, diff: 4.29 G
GPU #0: MSI RTX 3060 Ti - 61.20 MH/s, [T:37C, P:129W, F:70%, E:474kH/W], 1/1 R:0%
Shares/min: 1 (Avr. 0.556)
Uptime: 2 mins 30 secs | Algo: ethash | T-Rex v0.21.6
WD: 2 mins 33 secs, shares: 1/1 

20220117 23:53:13 ethash epoch: 467, block: 14023935, diff: 4.29 G
20220117 23:53:23 ethash epoch: 467, block: 14023936, diff: 4.29 G
20220117 23:53:39 WARN: Can't setup fan speed for [000200]: NVAPI_NVIDIA_DEVICE_NOT_FOUND, code -6

------------20220117 23:53:39 -------------
Mining at us1.ethermine.org:5555, diff: 4.29 G
GPU #0: MSI RTX 3060 Ti - 61.20 MH/s, 1/1 R:0%
Shares/min: 1 (Avr. 0.556)
Uptime: 3 mins | Algo: ethash | T-Rex v0.21.6
WD: 3 mins 3 secs, shares: 1/1 

20220117 23:53:49 WARN: Can't setup fan speed for [000200]: NVAPI_NVIDIA_DEVICE_NOT_FOUND, code -6
20220117 23:53:59 WARN: Can't setup fan speed for [000200]: NVAPI_NVIDIA_DEVICE_NOT_FOUND, code -6
20220117 23:54:05 WARN: GPU #0: MSI GeForce RTX 3060 Ti is idle, last activity was 32 secs ago
20220117 23:54:09 WARN: Can't setup fan speed for [000200]: NVAPI_NVIDIA_DEVICE_NOT_FOUND, code -6

------------20220117 23:54:09 -------------
Mining at us1.ethermine.org:5555, diff: 4.29 G
GPU #0: MSI RTX 3060 Ti - 61.20 MH/s, 1/1 R:0%
Shares/min: 1 (Avr. 0.556)
Uptime: 3 mins 30 secs | Algo: ethash | T-Rex v0.21.6
WD: 3 mins 33 secs, shares: 1/1 

20220117 23:54:10 WARN: GPU #0: MSI GeForce RTX 3060 Ti is idle, last activity was 37 secs ago
20220117 23:54:15 ethash epoch: 467, block: 14023937, diff: 4.29 G
20220117 23:54:15 WARN: GPU #0: MSI GeForce RTX 3060 Ti is idle, last activity was 42 secs ago
20220117 23:54:19 WARN: Can't setup fan speed for [000200]: NVAPI_NVIDIA_DEVICE_NOT_FOUND, code -6
20220117 23:54:20 WARN: GPU #0: MSI GeForce RTX 3060 Ti is idle, last activity was 47 secs ago
20220117 23:54:25 WARN: GPU #0: MSI GeForce RTX 3060 Ti is idle, last activity was 52 secs ago
20220117 23:54:29 WARN: Can't setup fan speed for [000200]: NVAPI_NVIDIA_DEVICE_NOT_FOUND, code -6
20220117 23:54:30 ethash epoch: 467, block: 14023938, diff: 4.29 G
20220117 23:54:30 WARN: GPU #0: MSI GeForce RTX 3060 Ti is idle, last activity was 57 secs ago
20220117 23:54:31 WARN: WATCHDOG: T-Rex has a problem with GPU, terminating...
20220117 23:54:32 WARN: WATCHDOG: recovering T-Rex

**Comment by trexminer** [comment] 2022-01-18 11:45
Duplicate of https://github.com/trexminer/T-Rex/issues/881

**Closed by trexminer** 2022-01-18 11:45 UTC
