### ISSUE TITLE
losing 600mh/s of ALEPH on T-Rex 0.25.8 compared to older one on dual mining

### ISSUE THREAD

**Issue by boymatthew95** [trexminer/T-Rex#1104] opened 2022-02-20 03:15 UTC
same overclock but losing 600mh/s worth of ALEPH on dual mining. tried increasing the c.clock by 100 but surprise2 it can't. Maybe because need to increase the PL too. But it is clearly not worth it.

**Comment by trexminer** [comment] 2022-02-20 06:07
Duplicate of https://github.com/trexminer/T-Rex/issues/1096

**Closed by trexminer** 2022-02-20 06:07 UTC
