### ISSUE TITLE
[Feature request] enable mclock for linux

### ISSUE THREAD

**Issue by Waffleboy** [trexminer/T-Rex#892] opened 2021-11-28 17:58 UTC
```
  --mclock                   Sets GPU memory clock offset in MHz.
                                   Requires running the miner with administrative privileges.
```

Currently mclock is only available for windows. Could this be enabled in linux too?

**Comment by trexminer** [comment] 2021-11-29 00:41
Duplicate of https://github.com/trexminer/T-Rex/issues/592

**Closed by trexminer** 2021-11-29 00:41 UTC
