### ISSUE TITLE
Unable to start T-Rex with "TREX: <big amount of numbers and letters> error.

### ISSUE THREAD

**Issue by edawtoc** [trexminer/T-Rex#330] opened 2021-03-21 20:41 UTC
Hi,

I cannot start my T-Rex again.
I am using Arch Linux and ethermine.org.
I switched to ethminer for some time and want to go back to T-Rex but it won't run anymore.

![Zrzut ekranu z 2021-03-21 21-38-00](https://user-images.githubusercontent.com/57065272/111920231-207d3e00-8a8e-11eb-8d7b-35376baa1948.png)

Starting on: eu1.ethermine.org:5555
 Using protocol: stratum1.
 Authorizing...
 Authorized successfully.
 ethash epoch: 402, block: 12084273, diff: 4.00 G
 ethash epoch: 402, block: 12084273, diff: 4.00 G
 ApiServer: HTTP server started on 127.0.0.1:4067
 ---------------------------------------------------
 For control navigate to: http://127.0.0.1:4067/trex
 ---------------------------------------------------
 ApiServer: Telnet server started on 127.0.0.1:4068
 WARN: GPU #1(000500): Gigabyte GeForce GTX 1080 Ti, intensity set to 22
 WARN: GPU #0(000200): Zotac GeForce GTX 1080 Ti, intensity set to 22
 TREX: eyJhIjoibTJ2YmVEZ0U3Nm9xTys0UDllZTBRQnZUUTlRYjVuMFlpQmpBbFpqeXJMOWIxSXJJa0F5MUk1NXFxVnhTMjRVQmxUWmNPQmdCOUtPVno5ZFZZQit3YnFKeFgrakw5M2ZpYmgxckVaVEljaGc9IiwiYiI6Ing4TWlnOHdrcXNmblpnZzYzNEsyaVE9PSJ9Cg==
 WARN: Miner is going to shutdown...
 WARN: GPU #2(000a00): Gigabyte GeForce GTX 1080 Ti, intensity set to 22
 WARN: GPU #3(000c00): Zotac GeForce GTX 1080 Ti, intensity set to 22
 Main loop finished. Cleaning up resources...

**Comment by Raymoz101** [comment] 2021-03-21 21:09
That long string looks like a cypher to me. 

Can you try without "ssl" in the server URL and see if you get the same result?

**Comment by edawtoc** [comment] 2021-03-21 21:12
I have removed SSL and change port to 4444 but unfortunately no change.

**Comment by Raymoz101** [comment] 2021-03-21 21:20
Make sure it was the full URL with "tcp" replacing ssl:

stratum+tcp://eu1.ethermine.org:4444

Also, noticed you're starting with no -w for worker name. 

Aside from the basics there. 

Is there anything extra in the log file?

**Comment by mreilaender** [comment] 2021-03-22 08:16
Same problem here, yesterday everything worked fine, today I'm getting the same error. I enabled "user protocol dump" with the `-P` CLI option and [this is the output](https://pastebin.com/3hyXVMAU).

**Comment by trexminer** [comment] 2021-03-22 09:32
Please check if the test builds from https://github.com/trexminer/T-Rex/issues/296 fix the issue

**Comment by FoxelFox** [comment] 2021-03-23 18:11
Same here after Driver Update from Manjaro
The test builds works fine

**Comment by trexminer** [comment] 2021-03-28 12:22
Should be fixed in https://github.com/trexminer/T-Rex/releases/tag/0.19.14

**Comment by zacariaz** [comment] 2021-04-23 10:54
I have the same issue.
I suspect it's not actually a miner issue, as toher, though not all, miners also fail, but I honestly don't know.
I'm running arcolinux, so it could, somehow, be an arch linux related issue. Too new Linux kernel?
I am mining to the same pool.
t-rex -a ethash -o stratum+tcp://eu1.ethermine.org:4444 -u xxxxxxx -p x -w worker

Would be nice to get an actual error message. For now, I'm using hiveos in a separate rig, for my 3090, also with t-rex and the same arguments, but I'd very much like to keep it to one rig, and not use hiveos, which doesn't really work for me.


Best regards.

**Comment by trexminer** [comment] 2021-04-23 11:08
@zacariaz could you please copy and paste that cryptic error message here please?
Also, are you running the latest t-rex (0.20.1 at the time of writing)?

**Comment by zacariaz** [comment] 2021-04-23 14:30
@trexminer 
The message:
20210423 10:08:22 TREX: eyJhIjoiQ1RFOXp2L0pDQWZFMDRibmswR1l6eTZsTUZ6M21BMStEN0RNRG5aajM4aHMxRmRtVklKMTNyeXJ0bUFYR3BiL0Qwa3lQZHFNYVFid0VwSmdlKzdXeEM3VXpadTIxOVh6VlVIeGE3T1hBQWs9IiwiYiI6IkdYY1lGYVFJb3Vid3hTL05FZmdKc2c9PSJ9Cg==

Version 0.20.1 from the arch user repository (trex-bin)

I won't be home for the next couple of days, so I may not be able to answer every question, but I'll try my best.
I'm probably running kernel 5.11, and Nvidia 465, cuda 11.3 (I think).
Thanks for the attention.

**Comment by trexminer** [comment] 2021-04-24 11:53
@zacariaz thanks. Should be fixed in https://github.com/trexminer/T-Rex/releases/tag/0.20.3, let me know if the issue persists

**Comment by zacariaz** [comment] 2021-04-24 13:41
@trexminer 
Looking forward to trying it out. I must say that I'm impressed with the swift action.

**Comment by zacariaz** [comment] 2021-04-26 08:36
@trexminer 
I'm happy to say that the problem is solved.

**Closed** 2021-04-26 10:09 UTC

**Comment by zacariaz** [comment] 2021-04-27 12:56
@trexminer 
Well, it would seem that I was mistaken, at least in part. It will actually get far enough to actually mine now, but...
`20210427 14:53:28 TREX: eyJhIjoiQlJDaVlzMUcwRVNDbEVDUHNFSCtUYXZuK0tETWxZekkrSldhWlJBbG9UY01pYkFvdklGTytmSzVpUW1UNFJlclhpM3JXWEtuWTJYTHlveGpSZlM5MWdYNDA5Z3dKSHpKOEZyOGtXMmFUN1NDMi92djlvTk0rUXV6Tzd5RUhJOGoxeUIwYkF4bzVDajdqUHdmTjVDOUdKUXQrUitIYkFvR0tGSjZrMG5HNHQyb2ZFanNkVFVXWXY4K3lXK0ZMOGx4ZGgvY2MxTHNSU0pkQTBHZFd5VEprdlU0OFZsQUtNRGgxeXRWTkhEUFlySEdtZVRTRTZPeWVSMFdOZ09wT2dIZFZMNEdjMnBSOUN2d09oaUZzZmJiWmc9PSIsImIiOiI2WHBmNEQyWEswcHBtSmtheVVrOWtBPT0ifQo=
20210427 14:53:28 WARN: Miner is going to shutdown...`

It is very sporadic now. Sometimes it happens early, and sometimes it takes a while.
