### ISSUE TITLE
GPU Memory temperature?

### ISSUE THREAD

**Issue by ziyangwang007** [trexminer/T-Rex#278] opened 2021-03-10 13:09 UTC
Hi, thank you for your amazing mining software!

I have been mining with T-Rex for two months with my 4 RTX 3090, 1 RTX 3080 and 2 RTX 3060ti.

I am just concerned about the GPU Memory temperature problem, because lots of people say RTX 30 series GDDR6X could suffer seriously high memory temperature.

In windows, it seems there is a software to monitor GPU Core and also Memory temperature. but I use the Linux Ubuntu system, is it possible to monitor GPU Memory temperature?

Thank you very much.
:)

**Comment by trexminer** [comment] 2021-03-11 09:15
Duplicate of https://github.com/trexminer/T-Rex/issues/236

**Closed by trexminer** 2021-03-11 09:15 UTC
