### ISSUE TITLE
Displayed difficulty not updating

### ISSUE THREAD

**Issue by samu01** [trexminer/T-Rex#131] opened 2021-01-10 04:18 UTC
The displayed difficulty does not seem to be updating.

I am mining ETH on Hiveon pool and when I start mining the pool gives me work that has a difficulty of 5000 MH, after that it adjusts to 1250 MH, but on the miner it still says "Mining at ru-eth.hiveon.net:24443, diff: 5.00 Gh"

T-Rex v0.19.7

**Comment by trexminer** [comment] 2021-01-14 13:36
Could you send the log file please? We can't reproduce this issue.

**Comment by samu01** [comment] 2021-01-14 18:40
[Here is my latest log file](https://mega.nz/file/OoxlyaZB#aYR4oXFXbINDQCbgOSNEvDb5PVh6feDDAJtT_sztXGM)

**Comment by trexminer** [comment] 2021-01-15 08:19
Thanks. I had a look, but there are no diff update messages from the pool as far as I can see. How do you know the pool adjusted the difficulty?

**Comment by samu01** [comment] 2021-01-15 08:53
Because with an other miner I do see the difficulty update, and also if I have 62 MH/s, I should not get 2.8 shares per minute with 5000 MH difficulty. I should be getting around 0.744 shares per minute.

But if we calculate with 1250 MH difficulty, I should be getting around 2.975 shares per minute which is close to what I am getting.

[In this image of the other miner, you can see the difficulty update](https://i.imgur.com/HI5SozY.png)

**Comment by trexminer** [comment] 2021-01-15 09:41
Thanks for confirming that. We've found where the issue originates from and will fix it in the next version.

**Comment by trexminer** [comment] 2021-01-19 13:28
Hi @samu01. This issue should be fixed in 0.19.9, please check it out.

**Comment by samu01** [comment] 2021-01-19 13:38
Yep, it does seem to be working correctly now. Thanks for the fix.

**Closed** 2021-01-19 22:23 UTC
