### ISSUE TITLE
RTX 3080 Ti NVML: can't get power for GPU #1, Can't get fan speed, can't get mem/core clock

### ISSUE THREAD

**Issue by yobokies** [trexminer/T-Rex#928] opened 2021-12-14 04:36 UTC
i'm currently using RTX 3080 Ti brand new with brand new PCIE Riser. i can start mining for 1-2 minutes until is shows
Can't get fan speed, error code 15
Can't get power for GPU, error code 15
Can't get mem/core clock for GPU, error code 17

after that T-rex miner keep on saying RTX 3080 Ti is inactive and it goes to blue screen. is it common issue? how do i fix this?
![InkedWhatsApp Image 2021-12-14 at 11 35 36 AM_LI](https://user-images.githubusercontent.com/96093711/145934249-2cdff86c-96ad-439d-9e97-fa34cad22617.jpg)

please help me fix this

currently i'm running the miner using Nvidia Driver 472.12 & Trex miner 0.28 in Windows 10
my afterburner setting
power limit = 83%
core clock = -500
memory clock = +900
fan = 80%

**Comment by trexminer** [comment] 2021-12-14 06:02
Duplicate of https://github.com/trexminer/T-Rex/issues/322

**Closed by trexminer** 2021-12-14 06:02 UTC

**Comment by yobokies** [comment] 2021-12-14 06:21
> Duplicate of #322

is updating the driver will solve the issue?

**Comment by DragonSerW** [comment] 2021-12-25 12:20
yobokies, yes, driver updating will solve the problemo for sure! ))
https://www.cryptoprofi.info/?p=5519: > set in BIOS the baud rate for the PCI-E line to GEN 2 or 1;
Where can I find that very option?
> Материнская плата Gigabyte Z590M GAMING X, LGA 1200, Intel Z590, mATX, Ret
