### ISSUE TITLE
Overclocking for Linux (mclock) and fan control with target core temperature is very necessary!

### ISSUE THREAD

**Issue by man55** [trexminer/T-Rex#603] opened 2021-09-01 08:02 UTC
Overclocking for Linux (mclock) and fan control with target core temperature is very necessary!

**Comment by trexminer** [comment] 2021-09-01 14:14
Duplicate of https://github.com/trexminer/T-Rex/issues/592

**Closed by trexminer** 2021-09-01 14:14 UTC
