### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by HepatitisB** [trexminer/T-Rex#415] opened 2021-04-15 18:57 UTC
Can't find nonce with device [ID=2, GPU #2], cuda exception in [StreamXontext,structstruture].....Ethash::KernelLaucnhTag;;synchronize, 52, CUDA_ERROR_UNKNOWN.....

WARN: WATCHDOG: TREX does not exist anymore, restarting...
TRex has a problem with GPU, terminating....
recovering TRex....

Does this deal with my overclocking, riser. motherboard slot...? It has happened 3 times within 3 days

![photo_2021-04-15_14-57-23](https://user-images.githubusercontent.com/20805377/114923514-eb4cdd00-9dfa-11eb-8ddf-e9e771a2b558.jpg)

**Comment by trexminer** [comment] 2021-04-16 01:32
Yes, it's most likely a hardware related issue - check risers, cables, power supply etc.

**Comment by trexminer** [comment] 2021-04-16 01:36
Duplicate of https://github.com/trexminer/T-Rex/issues/226

**Closed by trexminer** 2021-04-16 01:36 UTC

**Comment by biancob** [comment] 2021-04-16 07:15
I had the same issue and solved it by removing --mclock, --cclock, --pl, --fan params from config. Running now for 24 hours without single crash, OC via AB.

**Comment by machinekoder** [comment] 2021-04-23 07:08
@biancob In your case same OC settings via AB solved this problem?

**Comment by biancob** [comment] 2021-04-23 07:26
Definitely. The same OC settings via AB just works fine. Of course you need to delay the OC until DAG is built.
