### ISSUE TITLE
Unable to mine Conflux using T-REX ... Reason - Device does not have enough free memory to hold the DAG.. working fine with NBMINER

### ISSUE THREAD

**Issue by 21Noob** [trexminer/T-Rex#1091] opened 2022-02-17 21:57 UTC
Getting Error :-
"TREX: Can't find nonce with device [ID=0, GPU #0], Device does not have enough free memory to hold the DAG for epoch 65. Required: 5.08 GB, free: 5.02 GB."
I have 2 rtx 2060-
1.Gigabyte GeForce RTX 2060 OC edition.
2.Zotac Gaming RTX 2060
unable to mine conflux now with t-rex miner... able to do it before when i was having only 1 gpu.. tried everything almost.. increasing paging file , enable CPU graphic etc. but gives the same error...
Then i switched to NBminer and i have no issues... I can now mine conflux with NBMiner but not with T-REX...
It is not gpu fault... it has something to do with T-REX itself.
Please fix it or someone please help. I love to use T-REX

**Comment by trexminer** [comment] 2022-02-18 05:39
Duplicate of https://github.com/trexminer/T-Rex/issues/1007

**Closed by trexminer** 2022-02-18 05:39 UTC
