### ISSUE TITLE
ETH+Zil+Alph PLEASE!

### ISSUE THREAD

**Issue by mflanagan1041** [trexminer/T-Rex#1088] opened 2022-02-16 14:32 UTC
i have been trying to mine ETH+Zil on Ezil and other zil pools and the miner will not mine if using dual miner with Alph. This is in windows. I can get it to work in hiveos but not windows. is there a quick fix to this?

**Comment by gigabyteminer** [comment] 2022-02-16 18:18
Its working on ezil+ alph

**Comment by gigabyteminer** [comment] 2022-02-16 18:18
![4AC4A9FB-0D42-4707-9F16-AAB0BEE45E99](https://user-images.githubusercontent.com/91029365/154330094-eee7e554-b758-403f-927d-6467abbbfec0.png)

**Comment by trexminer** [comment] 2022-02-16 21:26
Duplicate of https://github.com/trexminer/T-Rex/issues/1088

**Closed by trexminer** 2022-02-16 21:26 UTC
