### ISSUE TITLE
Trex Eth+Ton Please !!!!

### ISSUE THREAD

**Issue by Ricco59163** [trexminer/T-Rex#1175] opened 2022-03-19 20:53 UTC
Hi all , can you update the T-rex version for Dual mining  Eth+Ton ?

thx

**Comment by zhanko73** [comment] 2022-03-20 00:25
> Hi all , can you update the T-rex version for Dual mining Eth+Ton ?
> 
> thx

What about the lolminer? It has ETH+TON. Have you tried already?

**Comment by samy63** [comment] 2022-03-23 09:59
Hello

yes please to include dual mining ETH+TON

i prefer trex than lolminer. 

thank you in advance

**Comment by trexminer** [comment] 2022-03-24 17:03
Duplicate of https://github.com/trexminer/T-Rex/issues/1035

**Closed by trexminer** 2022-03-24 17:03 UTC
