### ISSUE TITLE
Please provide TON coin support in dual mining 

### ISSUE THREAD

**Issue by ROCKET0101** [trexminer/T-Rex#1058] opened 2022-02-07 18:53 UTC
Please provide TON coin support in dual mining t-rex developers..

**Comment by youngjuning** [comment] 2022-02-08 06:06
+1

**Comment by kerimsagol1** [comment] 2022-02-08 07:19
+1

**Comment by kerimsagol1** [comment] 2022-02-08 07:20
+1

**Comment by Stiffman** [comment] 2022-02-08 14:31
+1

**Comment by cool2hatex** [comment] 2022-02-08 20:09
+1

**Comment by corndev27** [comment] 2022-02-08 22:37
+1

**Comment by rheyhannh** [comment] 2022-02-09 08:26
+1

**Comment by trexminer** [comment] 2022-02-09 15:26
Duplicate of https://github.com/trexminer/T-Rex/issues/1035

**Closed by trexminer** 2022-02-09 15:26 UTC
