### ISSUE TITLE
autolykos fail on NH

### ISSUE THREAD

**Issue by Quake4** [trexminer/T-Rex#1059] opened 2022-02-07 19:30 UTC
![image](https://user-images.githubusercontent.com/29517243/152858305-63327417-3241-4691-a7c6-9b43dce7fc9b.png)

**Comment by trexminer** [comment] 2022-02-09 15:23
Duplicate of https://github.com/trexminer/T-Rex/issues/1020

**Closed by trexminer** 2022-02-09 15:23 UTC
