### ISSUE TITLE
这种应该怎么解决

### ISSUE THREAD

**Issue by gudaojun** [trexminer/T-Rex#294] opened 2021-03-15 07:27 UTC
![屏幕截图 2021-03-15 152650](https://user-images.githubusercontent.com/54383441/111117753-e2ba7a00-85a2-11eb-8a3e-30883812715d.png)
It seems that mining has not started, and the power is not displayed. How to deal with this

**Comment by trexminer** [comment] 2021-03-15 09:20
Duplicate of https://github.com/trexminer/T-Rex/issues/266

**Closed by trexminer** 2021-03-15 09:20 UTC
