### ISSUE TITLE
When unlock ETH-Toncoin dual mining?

### ISSUE THREAD

**Issue by Samuelworker** [trexminer/T-Rex#1073] opened 2022-02-10 02:05 UTC
I think trex is the best mining software for NVDIA cards especially LHR cards. Please add unlock ETH-Toncoin dual mining

**Comment by trexminer** [comment] 2022-02-10 06:22
Duplicate of https://github.com/trexminer/T-Rex/issues/1035

**Closed by trexminer** 2022-02-10 06:22 UTC
