### ISSUE TITLE
Dual mining, ETH+TON mining request 

### ISSUE THREAD

**Issue by GTreaper** [trexminer/T-Rex#1044] opened 2022-02-05 01:12 UTC
Prefer Trexminer over all and use it on all my nvidia rigs. Would love to see TON+ETH dual mining getting added!
Thanks for a great miner ⛏️

**Comment by trexminer** [comment] 2022-02-05 07:58
Duplicate of https://github.com/trexminer/T-Rex/issues/1035

**Closed by trexminer** 2022-02-05 07:58 UTC

**Comment by AlbaraaSG** [comment] 2022-04-16 11:38
+1
