### ISSUE TITLE
Invalid extranonce2 size when run autolykos2 algo with NiceHash pool.

### ISSUE THREAD

**Issue by i1itione** [trexminer/T-Rex#976] opened 2022-01-03 17:15 UTC
I'm using T-Rex 0.24.8, and this issue occurred since last week.

20220104 00:50:21 autolykos2 [FAIL] 5505/5703 - Invalid extranonce2 size., 173ms ... GPU #0
20220104 00:50:27 autolykos2 [FAIL] 5505/5704 - Invalid extranonce2 size., 177ms ... GPU #1
20220104 00:52:29 autolykos2 [FAIL] 5522/5722 - Invalid extranonce2 size., 183ms ... GPU #3
20220104 00:52:29 autolykos2 [FAIL] 5522/5723 - Invalid extranonce2 size., 173ms ... GPU #2

Is it NiceHash side problem?

Thanks for your help.

**Comment by maxpayne3d** [comment] 2022-01-04 21:37
+1. Exactly the same problem. Started right before holidays. I have 2 separate rigs and it happens on both of them and on all GPU's. And it looks like that error appears at exact same time for both rigs. 
Also getting error Job not found ever now and then.
Tried installing different drivers, using hiveos instead if Windows. Different OC settings. Nothing is working.
I already messaged to NIcehash support but doesn't look like they think it's on their side.

Any ideas ? 
Thank you.

**Comment by ppiwo** [comment] 2022-01-05 06:00
+1 here as well, started happening right before the holidays.

Seems to be an issue on Nicehash's end. I found a similar thread from ~3 months back with the Trex dev supposedly stating so.

`[14:38] trex: Technically speaking it's our bug, but when they approached me they said they'd fixed it on their side (stopped changing xnonce size essentially), so I ignored the problem. Turns out the problem is still there. We'll fix it on our side in future releases.`

The thread:
https://www.reddit.com/r/NiceHash/comments/pm676r/comment/hflrcg2/?utm_source=share&utm_medium=web2x&context=3

**Comment by maxpayne3d** [comment] 2022-01-05 17:33
T-rex team. That problems has been there for a while. May be that's about the time to fix it on your end so it doesn't happen every several months ? That would be much appreciated.

**Comment by ppiwo** [comment] 2022-01-06 06:40
@maxpayne3d you can always just switch to a mining pool such as WoolyPooly. That's what I did and so far so good 👍🏻

**Comment by maxpayne3d** [comment] 2022-01-06 18:29
The reason I'm using NiceHash is that I'm dual mining eth+ergo and NiceHash gives me a better profit comparing to mining to a pool.

**Comment by FunktasticLucky** [comment] 2022-01-17 04:15
I'm not recieving this error full bore and getting 100 percent failure rate on mining ERGO on nicehash.  Can T-Rex team PLEASE work on this issue? Going back to ethereum mining for now I guess.

**Comment by maxpayne3d** [comment] 2022-01-17 04:17
I tried NBminer today and they don't have this error. Trex problem is still persist.

**Comment by angelbbs** [comment] 2022-01-21 08:27
+100500

**Comment by i1itione** [comment] 2022-01-30 18:12
It seems that this issue is solved currently by NiceHash pool side?

**Comment by FunktasticLucky** [comment] 2022-01-30 18:14
> 

No it.comes and goes. If you let it run long enough it just corrects but you lose out on that hour or so that it's happening.

**Comment by maxpayne3d** [comment] 2022-01-30 22:05
Right. I think it might be better these days but still randomly happens.

**Comment by trexminer** [comment] 2022-09-29 15:22
Should be fixed in 0.26.6

**Closed by trexminer** 2022-09-29 15:22 UTC
