### ISSUE TITLE
Works on benchmark mode but fails to mine

### ISSUE THREAD

**Issue by ironstarfish** [trexminer/T-Rex#185] opened 2021-02-05 17:27 UTC
Works when benchmark flag is set but fails to run when flag is removed.

Command:
./t-rex -a ethash -o stratum+ssl://us1.ethermine.org:5555 -u 0xXXX -p x -w XXX -d 1 --pci-indexing --gpu-init-mode 1 --mt 6 -i 24.5

T-Rex NVIDIA GPU miner v0.19.9  -  [CUDA v11.10 | Linux]
Linux: 5.10.12-xanmod1-cacule-1-cacule
NVIDIA-SMI 460.39       Driver Version: 460.39       CUDA Version: 11.2 

 WARN: GPU #1(000b00): Zotac GeForce GTX 1080 Ti, intensity set to 24.5, mtweak 6
 ethash epoch: 393, block: 11797566, diff: 4.00 G
 ethash epoch: 393, block: 11797566, diff: 4.00 G
 TREX: eyJhIjoiRFMyWHArWUI1NnRiRjhUUDkra....
 WARN: Miner is going to shutdown...
 Main loop finished. Cleaning up resources...

Feb 05 12:20:47 XXX audit[63175]: ANOM_ABEND auid=1000 uid=0 gid=0 ses=2 subj==/home/miner/Apps/t-rex_0.19.9/t-rex//null-/home/miner/Apps/t-rex_0.19.9/t-rex (complain) pid=63175 comm="miner0" exe="/home/miner/Apps/t-rex_0.19.9/t-rex" sig=11 res=1
Feb 05 12:20:47 XXX audit: BPF prog-id=205 op=LOAD
Feb 05 12:20:47 XXX audit: BPF prog-id=206 op=LOAD
Feb 05 12:20:47 XXX systemd[1]: Started Process Core Dump (PID 63279/UID 0).
Feb 05 12:20:47 XXX audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-coredump@1-63279-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Feb 05 12:20:48 XXX systemd-coredump[63280]: [🡕] Process 63175 (t-rex) of user 0 dumped core.

                                              Stack trace of thread 63269:
                                              #0  0x0000000000643ad6 n/a (/home/miner/Apps/t-rex_0.19.9/t-rex + 0x243ad6)
Feb 05 12:20:48 XXX systemd[1]: systemd-coredump@1-63279-0.service: Succeeded.

**Comment by trexminer** [comment] 2021-02-06 01:09
Could you please post the full line that starts with `TREX: eyJhIjoiRFMyWHArWUI1NnRiRjhUUDkra....`?

**Comment by ironstarfish** [comment] 2021-02-06 01:13
Here is the complete message
 TREX: eyJhIjoiNnFUOHZYd1BoRnNUdFIyaElOa0JxVElraXNLbVJHV3dPcDFGS0xaSEZwbUFYUmFaTlJLMGF1NnFxcVJNU0JjUCtJbXNxNkRMTGx6UkFHcTB1dFl5dGlkUndPMjJlOFJDc0VFMlBjRmJKUUtBL1l4d0VZSjZ1R3lOcWE3cGN1eloiLCJiIjoieWtwZE85OG9zSG4vTHZ6a3QwOGtmUT09In0K

**Comment by ironstarfish** [comment] 2021-02-06 01:17
Tried multiple times, I think this one matches the original string that I posted.
 TREX: eyJhIjoiRFMyWHArWUI1NnRiRjhUUDkraDB5WEV6ZnN3Y0xIL3VOYWNYaHB2SG5jV0NYNkVQS3U0NUw1bmQ1eUpmQm1ZVmgvSUcrT3RhLzNWOHA1Y1Z4TzIvTWQvQUY4QjdUQ2oweU90K0xma2lPMGpoajMybkxFZWgvVExKR1Baa2hZeHgiLCJiIjoiSlU1Y0NyVUdVQUE0M2dUc1htdkcxZz09In0K

**Comment by trexminer** [comment] 2021-02-06 01:23
Thanks much. It's a known issue, and will be fixed in the next version, hopefully within a couple of days.

**Comment by trexminer** [comment] 2021-02-09 11:36
@ironstarfish could you try 0.19.10 please?

**Comment by ironstarfish** [comment] 2021-02-09 15:24
Working fine now.  Thank you.

**Comment by kartof0nix** [comment] 2021-02-09 21:43
Experiencing same problem, though in version 0.19.10 :(
During benchmark I have hashrate of about 9000 kH/s, and find shares quite often.
While mining I have only 3 H/s and don't find any shares, even for longer runs.

Attached conf file.
[zap.txt](https://github.com/trexminer/T-Rex/files/5954445/zap.txt)


Benchmark command : t-rex.exe -c zap.txt -B
Output:
20210209 22:31:42 T-Rex NVIDIA GPU miner v0.19.10  -  [CUDA v10.0 | Windows]                                                                                                                                                                 20210209 22:31:42 r.fcc3b6574e6b                                                                                                                                                                                                             20210209 22:31:42                                                                                                                                                                                                                            20210209 22:31:42 NVIDIA Driver v452.41                                                                                                                                                                                                      20210209 22:31:42 CUDA devices available: 1                                                                                                                                                                                                  20210209 22:31:42                                                                                                                                                                                                                            20210209 22:31:42 WARN: BENCHMARK MODE (ethash)                                                                                                                                                                                              20210209 22:31:42 WARN: EPOCH 1                                                                                                                                                                                                              20210209 22:31:42                                                                                                                                                                                                                            20210209 22:31:42 === MAIN POOL === | back to main in 10 mins |                                                                                                                                                                              20210209 22:31:42 URL : stratum+tcp://eth.ss.poolin.com:443                                                                                                                                                                                  20210209 22:31:42 USER: ethnakeydp.001                                                                                                                                                                                                       20210209 22:31:42 PASS: 123                                                                                                                                                                                                                  20210209 22:31:42 WRK : ethnakeydp.001                                                                                                                                                                                                       20210209 22:31:42                                                                                                                                                                                                                            20210209 22:31:42 URL : stratum+tcp://eth.ss.poolin.com:1883                                                                                                                                                                                 20210209 22:31:42 USER: ethnakeydp.001                                                                                                                                                                                                       20210209 22:31:42 PASS: 123                                                                                                                                                                                                                  20210209 22:31:42 WRK : ethnakeydp.001                                                                                                                                                                                                       20210209 22:31:42                                                                                                                                                                                                                            20210209 22:31:42 URL : stratum+tcp://eth.ss.poolin.com:25                                                                                                                                                                                   20210209 22:31:42 USER: ethnakeydp.001                                                                                                                                                                                                       20210209 22:31:42 PASS: 123                                                                                                                                                                                                                  20210209 22:31:42 WRK : ethnakeydp.001                                                                                                                                                                                                       20210209 22:31:42                                                                                                                                                                                                                            20210209 22:31:42 WARN: unknown vendor id 0x103c of GPU nvml_id=#0                                                                                                                                                                           20210209 22:31:43 WARN: GPU #0(000100): GeForce GTX 1650, intensity set to 20                                                                                                                                                                20210209 22:31:44 WARN: NVML: can't get fan speed for GPU #0, not supported                                                                                                                                                                  20210209 22:31:46 GPU #0: generating DAG 1.01 GB for epoch 1 ...                                                                                                                                                                             20210209 22:31:50 GPU #0: DAG generated [crc: 20897c68, time: 4507 ms], memory left: 2.23 GB                                                                                                                                                 20210209 22:32:11 GPU #0: using kernel #2                                                                                                                                                                                                    20210209 22:32:12 Total: 9047.08 kH/s                                                                                                                                                                                                        20210209 22:32:14 Total: 8975.48 kH/s                                                                                                                                                                                                        20210209 22:32:16 Total: 8957.33 kH/s                                                                                                                                                                                                        20210209 22:32:18 Total: 8963.32 kH/s                                                                                                                                                                                                        20210209 22:32:20 Total: 8961.58 kH/s                                                                                                                                                                                                        20210209 22:32:22 Total: 8984.38 kH/s                                                                                                                                                                                                        20210209 22:32:25 Total: 8983.34 kH/s                                                                                                                                                                                                        20210209 22:32:27 Total: 8994.76 kH/s                                                                                                                                                                                                        20210209 22:32:29 Total: 8997.25 kH/s                                                                                                                                                                                                        20210209 22:32:31 Total: 8990.60 kH/s                                                                                                                                                                                                        20210209 22:32:33 Total: 8980.69 kH/s                                                                                                                                                                                                        20210209 22:32:34 Found 1 share(s)                                                                                                                                                                                                           20210209 22:32:35 Total: 8984.29 kH/s                                                                                                                                                                                                        20210209 22:32:37 Total: 8983.80 kH/s                                                                                                                                                                                                        20210209 22:32:37 Found 1 share(s)      

Mine command: t-rex.exe -c zap.txt 
Output:
20210209 22:36:41 T-Rex NVIDIA GPU miner v0.19.10  -  [CUDA v10.0 | Windows]                                                                                                                                                                 20210209 22:36:41 r.fcc3b6574e6b                                                                                                                                                                                                             20210209 22:36:41                                                                                                                                                                                                                            20210209 22:36:41 NVIDIA Driver v452.41                                                                                                                                                                                                      20210209 22:36:41 CUDA devices available: 1                                                                                                                                                                                                  20210209 22:36:41                                                                                                                                                                                                                            20210209 22:36:41 WARN: DevFee 1% (ethash)                                                                                                                                                                                                   20210209 22:36:41                                                                                                                                                                                                                            20210209 22:36:41 === MAIN POOL === | back to main in 10 mins |                                                                                                                                                                              20210209 22:36:41 URL : stratum+tcp://eth.ss.poolin.com:443                                                                                                                                                                                  20210209 22:36:41 USER: ethnakeydp.001                                                                                                                                                                                                       20210209 22:36:41 PASS: 123                                                                                                                                                                                                                  20210209 22:36:41 WRK : ethnakeydp.001                                                                                                                                                                                                       20210209 22:36:41                                                                                                                                                                                                                            20210209 22:36:41 URL : stratum+tcp://eth.ss.poolin.com:1883                                                                                                                                                                                 20210209 22:36:41 USER: ethnakeydp.001                                                                                                                                                                                                       20210209 22:36:41 PASS: 123                                                                                                                                                                                                                  20210209 22:36:41 WRK : ethnakeydp.001                                                                                                                                                                                                       20210209 22:36:41                                                                                                                                                                                                                            20210209 22:36:41 URL : stratum+tcp://eth.ss.poolin.com:25                                                                                                                                                                                   20210209 22:36:41 USER: ethnakeydp.001                                                                                                                                                                                                       20210209 22:36:41 PASS: 123                                                                                                                                                                                                                  20210209 22:36:41 WRK : ethnakeydp.001                                                                                                                                                                                                       20210209 22:36:41                                                                                                                                                                                                                            20210209 22:36:41 Starting on: eth.ss.poolin.com:443                                                                                                                                                                                         20210209 22:36:41 WARN: unknown vendor id 0x103c of GPU nvml_id=#0                                                                                                                                                                           20210209 22:36:41 ApiServer: HTTP server started on 0.0.0.0:4067                                                                                                                                                                             20210209 22:36:41 -------------------------------------------------------                                                                                                                                                                    20210209 22:36:41 For control navigate to: http://192.168.0.150:4067/trex                                                                                                                                                                    20210209 22:36:41 -------------------------------------------------------                                                                                                                                                                    20210209 22:36:41 ApiServer: Telnet server started on 0.0.0.0:4068                                                                                                                                                                           20210209 22:36:42 WARN: GPU #0(000100): GeForce GTX 1650, intensity set to 20                                                                                                                                                                20210209 22:36:42 Using protocol: stratum1.                                                                                                                                                                                                  20210209 22:36:42 Authorizing...                                                                                                                                                                                                             20210209 22:36:42 Authorized successfully.                                                                                                                                                                                                   20210209 22:36:42 ethash epoch: 394, block: 505, diff: 8.59 G                                                                                                                                                                                20210209 22:36:42 ethash epoch: 394, block: 505, diff: 8.59 G                                                                                                                                                                                20210209 22:36:42 WARN: NVML: can't get fan speed for GPU #0, not supported                                                                                                                                                                  20210209 22:36:54 WARN: GPU #0: not enough memory to hold the full DAG for epoch 394.                                                                                                                                                        20210209 22:36:54 WARN: GPU #0: effective hashrate will be ~0.0% of its usual value                                                                                                                                                          20210209 22:36:54 GPU #0: generating DAG 3.24 GB (79.49% of full size) for epoch 394 ...                                                                                                                                                     20210209 22:37:10 GPU #0: DAG generated [crc: 069608b6(!), time: 16203 ms], memory left: 0.00 B                                                                                                                                              20210209 22:37:42                                                                                                                                                                                                                            20210209 22:37:42 Mining at eth.ss.poolin.com:443, diff: 8.59 G                                                                                                                                                                              20210209 22:37:42 GPU #0: GTX 1650 - 4.00 H/s, [T:46C, P:25W, E:0.18H/W]                                                                                                                                                                     20210209 22:37:42 Shares/min: 0                                                                                                                                                                                                              20210209 22:37:42 Uptime: 1 min | Algo: ethash | T-Rex v0.19.10                                                                                                                                                                              20210209 22:37:42                                                                                                                                                                                                                            20210209 22:37:53 ethash epoch: 394, block: 505, diff: 4.29 G                                                                                                                                                                                20210209 22:37:53 ethash epoch: 394, block: 505, diff: 2.15 G                                                                                                                                                                                20210209 22:38:12                                                                                                                                                                                                                            20210209 22:38:12 Mining at eth.ss.poolin.com:443, diff: 2.15 G                                                                                                                                                                              20210209 22:38:12 GPU #0: GTX 1650 - 4.00 H/s, [T:48C, P:26W, E:0.16H/W]                                                                                                                                                                     20210209 22:38:12 Shares/min: 0                                                                                                                                                                                                              20210209 22:38:12 Uptime: 1 min 30 secs | Algo: ethash | T-Rex v0.19.10                                                                                                                                                                      20210209 22:38:12                                                                                                                                                                                                                            20210209 22:38:42                                                                                                                                                                                                                            20210209 22:38:42 Mining at eth.ss.poolin.com:443, diff: 2.15 G                                                                                                                                                                              20210209 22:38:42 GPU #0: GTX 1650 - 4.00 H/s, [T:49C, P:25W, E:0.16H/W]                                                                                                                                                                     20210209 22:38:42 Shares/min: 0                                                                                                                                                                                                              20210209 22:38:42 Uptime: 2 mins 1 sec | Algo: ethash | T-Rex v0.19.10                                                                                                                                                                       20210209 22:38:42                                                                                                                                                                                                                            20210209 22:39:12                                                                                                                                                                                                                            20210209 22:39:12 Mining at eth.ss.poolin.com:443, diff: 2.15 G                                                                                                                                                                              20210209 22:39:12 GPU #0: GTX 1650 - 3.00 H/s, [T:48C, P:26W, E:0.12H/W]                                                                                                                                                                     20210209 22:39:12 Shares/min: 0                                                                                                                                                                                                              20210209 22:39:12 Uptime: 2 mins 31 secs | Algo: ethash | T-Rex v0.19.10

**Comment by kartof0nix** [comment] 2021-02-09 22:07
Found the cause myself - I had < 4 GB GPU Mem

**Closed** 2021-02-09 23:05 UTC
