### ISSUE TITLE
Fails to run on Arch Linux - Can't initialize device [ID=0, GPU #0], can't initialize, code 2 (0x1)

### ISSUE THREAD

**Issue by ironstarfish** [trexminer/T-Rex#492] opened 2021-04-30 20:33 UTC
Linux X470 5.11.16-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 21 Apr 2021 17:22:09 +0000 x86_64 GNU/Linux

Log:
20210430 16:29:29 Authorized successfully.
20210430 16:29:29 ethash epoch: 411, block: 12343957, diff: 4.00 G
20210430 16:29:29 ethash epoch: 411, block: 12343957, diff: 4.00 G
**20210430 16:29:29 TREX: Can't initialize device [ID=0, GPU #0], can't initialize, code 2 (0x1)**
20210430 16:29:29 WARN: Miner is going to shutdown...
20210430 16:29:29 Main loop finished. Cleaning up resources...
20210430 16:29:29 ApiServer: stopped listening on 127.0.0.1:4067
20210430 16:29:29 ApiServer: stopped listening on 127.0.0.1:4068
20210430 16:29:31 T-Rex finished.
20210430 16:29:32 WARN: WATCHDOG: T-Rex does not exist anymore, restarting...
20210430 16:29:34 T-Rex NVIDIA GPU miner v0.20.3  -  [Linux]
20210430 16:29:34 r.fdd97e1996a9
20210430 16:29:34
20210430 16:29:34 NVIDIA Driver v465.27
20210430 16:29:34 CUDA devices available: 1

**Comment by trexminer** [comment] 2021-05-01 01:51
Duplicate of https://github.com/trexminer/T-Rex/issues/167

**Closed by trexminer** 2021-05-01 01:51 UTC
