### ISSUE TITLE
Then ETH + TON for LHR cards

### ISSUE THREAD

**Issue by DMX555** [trexminer/T-Rex#1084] opened 2022-02-15 11:55 UTC
Good day!

Then ETH + TON for LHR cards?

**Comment by servaldsl** [comment] 2022-02-15 18:53
lolminer did +alph and +ton
I'm a t-rex maximalist, hope a new version with TON will be released. Don't want to change my miner

**Comment by vruva** [comment] 2022-02-15 22:51
+1

**Comment by brawnman** [comment] 2022-02-16 04:57
+1

**Comment by trexminer** [comment] 2022-02-16 08:11
Duplicate of https://github.com/trexminer/T-Rex/issues/1035

**Closed by trexminer** 2022-02-16 08:11 UTC
