### ISSUE TITLE
T-Rex\Nvidia driver problems! Dev Response Please!

### ISSUE THREAD

**Issue by Globespy** [trexminer/T-Rex#847] opened 2021-11-17 22:04 UTC
It seems that all driver's beyond 472.12 cause a pattern of T-Rex unlocking events that result in hash rates on LHR cards (I have 3080ti) to drop to less than half, even as low as 12-15% of previous rates - I'm using T-Rex 0.24.5 and have tried and tested every subsequent Nvidia driver release, including the just launched 496.84 Hotfix, and the problems persist.

Has the T-Rex dev been able to rectify in the newest versions (0.24.7) or is it even something that's being investigated when 'mining only' miners are just rolling back to Nvidia 472.12? 
I use one of my machines to game and work on, so it mines only when I am not needing the full GPU resources, and there's thousands of others out there who mine part time, but the PC is primarily for gaming. That's a lot of 1% fees being missed when new games require the updated drivers (Forza Horizon 5 required new driver).
Thanks for reading!

**Comment by trexminer** [comment] 2021-11-19 02:10
Duplicate of https://github.com/trexminer/T-Rex/issues/845

**Closed by trexminer** 2021-11-19 02:10 UTC
